// Scenario seed → factory dispatch table. Pre-extraction this lived in
// prototypeScenario.ts as a 587-LOC if-chain; converted to a Map<string,
// factory> for compactness. Multi-seed factories (Black Forest / Arena
// terrain variants and the slice-12 validation fixture set) are
// enumerated explicitly so the table stays a flat 1-line-per-seed shape
// — easier to scan, easier to grep, no special cases at lookup time.

import {
  createAiDifficultyFixture,
  createAiEconomyFixture,
  createAiMonkFixture,
  createAiMonkHealFixture,
  createAiMonkRelicFixture,
  createAiPlannerFixture,
  createAiRushFixture,
  createAiScoutingResponseFixture,
  createAiWonderFixture,
  createAutoAggroArcherPursuitFixture,
  createAutoAggroIdleMilitiaInVisionFixture,
  createAutoAggroIdleMilitiaOutOfVisionFixture,
  createAutoAggroMonkSkipFixture,
  createAutoAggroPlayerMoveOverridesFixture,
  createAutoAggroSequentialTargetsFixture,
  createAutoAggroVillagerAdjacentFixture,
  createAutoAggroVillagerGatheringFixture,
  createAutoAggroVillagerNoPursuitFixture,
  createBlacksmithProgressionFixture,
  createBlockedStableSpawnFixture,
  createBlockingRulesFixture,
  createBoarAggroFixture,
  createBombardCannonMinRangeBlockedFixture,
  createBombardCannonVsBuildingFixture,
  createBuildingFootprintVisionFixture,
  createCamelVsCavalryFixture,
  createCamelVsHussarFixture,
  createCamelVsRamFixture,
  createCastleAgeFixture,
  createCastleAiTargetPriorityFixture,
  createCastleDefensiveFireFixture,
  createCastleFletchingFixture,
  createCastleGarrisonFixture,
  createCastleNonBritonsFixture,
  createCastleTownCenterFixture,
  createCastleUniqueFixture,
  createCastleUpgradesFixture,
  createCavalryArcherRangedFixture,
  createChampionVsArmoredHalberdierFixture,
  createChampionVsHalberdierFixture,
  createConquestDefeatFixture,
  createConquestVictoryFixture,
  createDoubleBlacksmithRaceFixture,
  createDoubleClickSelectionFixture,
  createFarmDepletionFixture,
  createFarmOwnershipFixture,
  createFarmReseedFixture,
  createFeudalAgeFixture,
  createFeudalBlacksmithFixture,
  createFeudalMarketFixture,
  createFeudalMissingPrereqFixture,
  createFeudalSkirmisherFixture,
  createFeudalSpearmanFixture,
  createFeudalStableFixture,
  createFeudalWatchTowerFixture,
  createFishFixture,
  createFogMemoryCastleDestroyEdgeFixture,
  createFogMemoryCastleEdgeFixture,
  createFogMemoryFixture,
  createFu3CastleEdgeRangeFixture,
  createFu3CastleFiveArchersFixture,
  createFu3CastleNoArchersFixture,
  createFu3CastleThreeArchersFixture,
  createFu3PalisadeWallFixture,
  createFu3StoneWallBlockingFixture,
  createFu3StoneWallCombatFixture,
  createFu3StoneWallFixture,
  createHalberdierVsCavalierFixture,
  createHalberdierVsKnightFixture,
  createHeavyCamelVsKnightFixture,
  createImperialAgeFixture,
  createImperialArbalestFixture,
  createImperialBlacksmithFixture,
  createImperialCastleBritonsFixture,
  createImperialCastleFixture,
  createImperialCastleFranksFixture,
  createImperialHalberdierFixture,
  createImperialMissingPrereqFixture,
  createImperialSiegeFixture,
  createImperialStableFixture,
  createImperialUpgradesFixture,
  createIsolatedScoutSpawnFixture,
  createLongbowmanRangedFixture,
  createLoomBrokeFixture,
  createLoomFixture,
  createLoomResearchedFixture,
  createMangonelMinRangeBlockedFixture,
  createMangonelOutsideMinRangeFixture,
  createMangonelRangedFixture,
  createMangonelVsKnightFixture,
  createMangonelVsSpearmanFixture,
  createMilitiaCombatFixture,
  createMilitiaLineFixture,
  createMiningCampFixture,
  createMixedSelectionFixture,
  createMonasteryFixture,
  createMonkConvertCleanupFixture,
  createMonkConvertFixture,
  createMonkConvertVisionFixture,
  createMonkDoubleConvertFixture,
  createMonkFlipFlopFixture,
  createMonkFogFixture,
  createMonkHealFixture,
  createMonkHealOverConvertFixture,
  createMonkHealthyFriendlyWithEnemyFixture,
  createMonkRelicDropCrampedFixture,
  createMonkRelicDropFixture,
  createMonkRelicFixture,
  createMoveTargetUnblocksFixture,
  createMovingEnemyAttackFixture,
  createMultiVillagerConstructionFixture,
  createSingleVillagerConstructionFixture,
  createNarrowCorridorFixture,
  createOnagerMinRangeBlockedFixture,
  createOrdersFixture,
  createPaladinFixture,
  createPikemanVsKnightFixture,
  createPikemanVsRamFixture,
  createRamVsBuildingFixture,
  createRamVsVillagerFixture,
  createRelicNotAllHeldFixture,
  createRelicShortCountdownFixture,
  createResourceDepletionFixture,
  createScenarioValidationFixture,
  createScorpionRangedFixture,
  createSheepMovementFixture,
  createSheepOwnershipFixture,
  createSheepVisionFixture,
  createSiegeRamVsBuildingFixture,
  createSiegeWorkshopFixture,
  createSkirmisherVsCavalryArcherFixture,
  createSpearmanVsCamelFixture,
  createTileSelectionCycleFixture,
  createTowerVsSiegePriorityFixture,
  createTownCenterDefenseFixture,
  createTrebuchetPackFixture,
  createTrebuchetVsBuildingFixture,
  createUnitShowcaseFixture,
  createUnitSharingFixture,
  createVillagerNoWoodDropoffFixture,
  createVillagerSelectionFixture,
  createWolfAggroFixture,
  createWonderDestroyedFixture,
  createWonderExistingFixture,
  createWonderImperialFixture,
  createWonderOwnerAfterConversionFixture,
  createWonderRelicTieFixture,
  createWonderShortCountdownFixture,
} from '../fixtures';
import { createArenaMap } from '../mapGeneration/arenaMap';
import { createBlackForestMap } from '../mapGeneration/blackForestMap';
import { createDefaultMap } from '../mapGeneration/defaultMap';
import type { PrototypeScenario } from '../prototypeScenario';

type ScenarioFactory = (seed: string) => PrototypeScenario;

const SCENARIO_FACTORIES: ReadonlyMap<string, ScenarioFactory> = new Map<string, ScenarioFactory>([
  ['conquest-victory-fixture', createConquestVictoryFixture],
  ['conquest-defeat-fixture', createConquestDefeatFixture],
  ['blocking-rules-fixture', createBlockingRulesFixture],
  ['unit-sharing-fixture', createUnitSharingFixture],
  ['feudal-missing-prereq-fixture', createFeudalMissingPrereqFixture],
  ['feudal-age-fixture', createFeudalAgeFixture],
  ['feudal-blacksmith-fixture', createFeudalBlacksmithFixture],
  ['feudal-stable-fixture', createFeudalStableFixture],
  ['blocked-stable-spawn-fixture', createBlockedStableSpawnFixture],
  ['isolated-scout-spawn-fixture', createIsolatedScoutSpawnFixture],
  ['castle-age-fixture', createCastleAgeFixture],
  ['castle-town-center-fixture', createCastleTownCenterFixture],
  ['multi-villager-construction-fixture', createMultiVillagerConstructionFixture],
  ['single-villager-construction-fixture', createSingleVillagerConstructionFixture],
  ['castle-upgrades-fixture', createCastleUpgradesFixture],
  ['imperial-upgrades-fixture', createImperialUpgradesFixture],
  ['imperial-age-fixture', createImperialAgeFixture],
  ['imperial-missing-prereq-fixture', createImperialMissingPrereqFixture],
  ['imperial-arbalest-fixture', createImperialArbalestFixture],
  ['imperial-halberdier-fixture', createImperialHalberdierFixture],
  ['pikeman-vs-knight-fixture', createPikemanVsKnightFixture],
  ['halberdier-vs-knight-fixture', createHalberdierVsKnightFixture],
  ['imperial-stable-fixture', createImperialStableFixture],
  ['camel-vs-hussar-fixture', createCamelVsHussarFixture],
  ['halberdier-vs-cavalier-fixture', createHalberdierVsCavalierFixture],
  ['imperial-castle-britons-fixture', createImperialCastleBritonsFixture],
  ['imperial-castle-franks-fixture', createImperialCastleFranksFixture],
  ['camel-vs-cavalry-fixture', createCamelVsCavalryFixture],
  ['spearman-vs-camel-fixture', createSpearmanVsCamelFixture],
  ['cavalry-archer-ranged-fixture', createCavalryArcherRangedFixture],
  ['skirmisher-vs-cavalry-archer-fixture', createSkirmisherVsCavalryArcherFixture],
  ['siege-workshop-fixture', createSiegeWorkshopFixture],
  ['imperial-siege-fixture', createImperialSiegeFixture],
  ['imperial-blacksmith-fixture', createImperialBlacksmithFixture],
  ['blacksmith-progression-fixture', createBlacksmithProgressionFixture],
  ['double-blacksmith-race-fixture', createDoubleBlacksmithRaceFixture],
  ['champion-vs-halberdier-fixture', createChampionVsHalberdierFixture],
  ['champion-vs-armored-halberdier-fixture', createChampionVsArmoredHalberdierFixture],
  ['militia-line-fixture', createMilitiaLineFixture],
  ['paladin-fixture', createPaladinFixture],
  ['heavy-camel-vs-knight-fixture', createHeavyCamelVsKnightFixture],
  ['fu3-castle-no-archers-fixture', createFu3CastleNoArchersFixture],
  ['fu3-castle-three-archers-fixture', createFu3CastleThreeArchersFixture],
  ['fu3-castle-five-archers-fixture', createFu3CastleFiveArchersFixture],
  ['fu3-castle-edge-range-fixture', createFu3CastleEdgeRangeFixture],
  ['fu3-stone-wall-fixture', createFu3StoneWallFixture],
  ['fu3-stone-wall-blocking-fixture', createFu3StoneWallBlockingFixture],
  ['fu3-stone-wall-combat-fixture', createFu3StoneWallCombatFixture],
  ['fu3-palisade-wall-fixture', createFu3PalisadeWallFixture],
  ['onager-min-range-blocked-fixture', createOnagerMinRangeBlockedFixture],
  ['siege-ram-vs-building-fixture', createSiegeRamVsBuildingFixture],
  ['bombard-cannon-vs-building-fixture', createBombardCannonVsBuildingFixture],
  ['bombard-cannon-min-range-blocked-fixture', createBombardCannonMinRangeBlockedFixture],
  ['imperial-castle-fixture', createImperialCastleFixture],
  ['trebuchet-pack-fixture', createTrebuchetPackFixture],
  ['trebuchet-vs-building-fixture', createTrebuchetVsBuildingFixture],
  ['mangonel-ranged-fixture', createMangonelRangedFixture],
  ['scorpion-ranged-fixture', createScorpionRangedFixture],
  ['tower-vs-siege-priority-fixture', createTowerVsSiegePriorityFixture],
  ['mangonel-vs-spearman-fixture', createMangonelVsSpearmanFixture],
  ['mangonel-vs-knight-fixture', createMangonelVsKnightFixture],
  ['mangonel-min-range-blocked-fixture', createMangonelMinRangeBlockedFixture],
  ['mangonel-outside-min-range-fixture', createMangonelOutsideMinRangeFixture],
  ['ram-vs-building-fixture', createRamVsBuildingFixture],
  ['ram-vs-villager-fixture', createRamVsVillagerFixture],
  ['pikeman-vs-ram-fixture', createPikemanVsRamFixture],
  ['camel-vs-ram-fixture', createCamelVsRamFixture],
  ['monastery-fixture', createMonasteryFixture],
  ['monk-heal-fixture', createMonkHealFixture],
  ['monk-convert-fixture', createMonkConvertFixture],
  ['monk-fog-fixture', createMonkFogFixture],
  ['monk-convert-vision-fixture', createMonkConvertVisionFixture],
  ['monk-heal-over-convert-fixture', createMonkHealOverConvertFixture],
  ['monk-healthy-friendly-with-enemy-fixture', createMonkHealthyFriendlyWithEnemyFixture],
  ['monk-double-convert-fixture', createMonkDoubleConvertFixture],
  ['monk-flip-flop-fixture', createMonkFlipFlopFixture],
  ['monk-convert-cleanup-fixture', createMonkConvertCleanupFixture],
  ['monk-relic-drop-fixture', createMonkRelicDropFixture],
  ['monk-relic-drop-cramped-fixture', createMonkRelicDropCrampedFixture],
  ['castle-unique-fixture', createCastleUniqueFixture],
  ['castle-non-britons-fixture', createCastleNonBritonsFixture],
  ['castle-defensive-fire-fixture', createCastleDefensiveFireFixture],
  ['castle-ai-target-priority-fixture', createCastleAiTargetPriorityFixture],
  ['longbowman-ranged-fixture', createLongbowmanRangedFixture],
  ['loom-fixture', createLoomFixture],
  ['loom-broke-fixture', createLoomBrokeFixture],
  ['loom-researched-fixture', createLoomResearchedFixture],
  // M7 units-beyond-circles: a visual-only showcase placing one P1 unit per
  // render role (capture target for the unit-silhouette change).
  ['unit-showcase-fixture', createUnitShowcaseFixture],
  ['castle-fletching-fixture', createCastleFletchingFixture],
  ['castle-garrison-fixture', createCastleGarrisonFixture],
  ['monk-relic-fixture', createMonkRelicFixture],
  ['wonder-imperial-fixture', createWonderImperialFixture],
  ['wonder-existing-fixture', createWonderExistingFixture],
  ['wonder-short-countdown-fixture', createWonderShortCountdownFixture],
  ['wonder-destroyed-fixture', createWonderDestroyedFixture],
  ['relic-short-countdown-fixture', createRelicShortCountdownFixture],
  ['relic-not-all-held-fixture', createRelicNotAllHeldFixture],
  ['wonder-relic-tie-fixture', createWonderRelicTieFixture],
  ['wonder-owner-after-conversion-fixture', createWonderOwnerAfterConversionFixture],
  ['feudal-spearman-fixture', createFeudalSpearmanFixture],
  ['feudal-skirmisher-fixture', createFeudalSkirmisherFixture],
  ['militia-combat-fixture', createMilitiaCombatFixture],
  ['moving-enemy-attack-fixture', createMovingEnemyAttackFixture],
  ['auto-aggro-idle-militia-in-vision-fixture', createAutoAggroIdleMilitiaInVisionFixture],
  ['auto-aggro-idle-militia-out-of-vision-fixture', createAutoAggroIdleMilitiaOutOfVisionFixture],
  ['auto-aggro-archer-pursuit-fixture', createAutoAggroArcherPursuitFixture],
  ['auto-aggro-player-move-overrides-fixture', createAutoAggroPlayerMoveOverridesFixture],
  ['auto-aggro-villager-adjacent-fixture', createAutoAggroVillagerAdjacentFixture],
  ['auto-aggro-villager-no-pursuit-fixture', createAutoAggroVillagerNoPursuitFixture],
  ['auto-aggro-villager-gathering-fixture', createAutoAggroVillagerGatheringFixture],
  ['auto-aggro-monk-skip-fixture', createAutoAggroMonkSkipFixture],
  ['auto-aggro-sequential-targets-fixture', createAutoAggroSequentialTargetsFixture],
  ['feudal-watch-tower-fixture', createFeudalWatchTowerFixture],
  ['ai-rush-fixture', createAiRushFixture],
  ['ai-planner-fixture', createAiPlannerFixture],
  ['ai-scouting-response-fixture', createAiScoutingResponseFixture],
  ['ai-difficulty-fixture', createAiDifficultyFixture],
  ['ai-monk-fixture', createAiMonkFixture],
  ['ai-monk-heal-fixture', createAiMonkHealFixture],
  ['ai-monk-relic-fixture', createAiMonkRelicFixture],
  ['ai-wonder-fixture', createAiWonderFixture],
  ['feudal-market-fixture', createFeudalMarketFixture],
  ['town-center-defense-fixture', createTownCenterDefenseFixture],
  ['mining-camp-fixture', createMiningCampFixture],
  ['fish-fixture', createFishFixture],
  ['villager-no-wood-dropoff-fixture', createVillagerNoWoodDropoffFixture],
  ['fog-memory-castle-edge-fixture', createFogMemoryCastleEdgeFixture],
  ['fog-memory-castle-destroy-edge-fixture', createFogMemoryCastleDestroyEdgeFixture],
  ['boar-aggro-fixture', createBoarAggroFixture],
  ['wolf-aggro-fixture', createWolfAggroFixture],
  ['orders-fixture', createOrdersFixture],
  ['ai-economy-fixture', createAiEconomyFixture],
  ['villager-selection-fixture', createVillagerSelectionFixture],
  ['double-click-selection-fixture', createDoubleClickSelectionFixture],
  ['mixed-selection-fixture', createMixedSelectionFixture],
  ['tile-selection-cycle-fixture', createTileSelectionCycleFixture],
  ['sheep-ownership-fixture', createSheepOwnershipFixture],
  ['sheep-movement-fixture', createSheepMovementFixture],
  ['sheep-vision-fixture', createSheepVisionFixture],
  ['resource-depletion-fixture', createResourceDepletionFixture],
  ['farm-depletion-fixture', createFarmDepletionFixture],
  ['farm-reseed-fixture', createFarmReseedFixture],
  ['farm-ownership-fixture', createFarmOwnershipFixture],
  ['move-target-unblocks-fixture', createMoveTargetUnblocksFixture],
  ['narrow-corridor-fixture', createNarrowCorridorFixture],
  ['fog-memory-fixture', createFogMemoryFixture],
  ['building-footprint-vision-fixture', createBuildingFootprintVisionFixture],
  // Slice 11: alternate playable maps. Both share the default
  // two-player layout; only terrain differs.
  ['black-forest-fixture', createBlackForestMap],
  ['black-forest', createBlackForestMap],
  ['arena-fixture', createArenaMap],
  ['arena', createArenaMap],
  // Slice 12 Task B: scenario-validation fixtures. Each seed exercises
  // one failure mode of the bridge-boot validation pass; the
  // `-ok-fixture` is the positive control.
  ['slice12-validation-ok-fixture', createScenarioValidationFixture],
  ['slice12-validation-out-of-bounds-fixture', createScenarioValidationFixture],
  ['slice12-validation-overlap-fixture', createScenarioValidationFixture],
  ['slice12-validation-unit-in-building-fixture', createScenarioValidationFixture],
  ['slice12-validation-resource-on-building-fixture', createScenarioValidationFixture],
  ['slice12-validation-resource-on-resource-fixture', createScenarioValidationFixture],
]);

// Look up `seed` in the table; falls back to `createDefaultMap` for
// unrecognized seeds (matches the pre-extraction behavior — the original
// if-chain ended with the same fallback). The DEFAULT_SEED short-circuit
// stays in the parent file because it shouldn't even hit the lookup.
export function dispatchScenario(seed: string): PrototypeScenario {
  const factory = SCENARIO_FACTORIES.get(seed);
  return factory ? factory(seed) : createDefaultMap(seed);
}
