// Every scenario seed the game knows, and the factory that builds it. Split out
// of ./dispatch.ts, which had grown past the 500-line budget purely by holding
// this table: the dispatcher is a two-line lookup, and the table is a flat
// one-line-per-seed list that only ever grows. Keeping them apart means adding
// a fixture touches the list and nothing else.


// One namespace import instead of naming every factory twice: the list had
// grown to 230 import lines plus 239 map entries and pushed the file past the
// 500-line budget on its own. `../fixtures` is a barrel, so this pulls in
// exactly what the named list did.
import * as fixtures from '../fixtures';
import { createArenaMap } from '../mapGeneration/arenaMap';
import { createBlackForestMap } from '../mapGeneration/blackForestMap';
import { createDefaultMap } from '../mapGeneration/defaultMap';
import {
  createCoastalMap,
  createFortressMap,
  createGoldRushMap,
  createIslandsMap,
  createNomadMap,
} from '../mapGeneration/standardVariantMaps';
import type { PrototypeScenario } from '../prototypeScenario';

type ScenarioFactory = (seed: string) => PrototypeScenario;

export const SCENARIO_FACTORIES: ReadonlyMap<string, ScenarioFactory>
  = new Map<string, ScenarioFactory>([
  ['conquest-victory-fixture', fixtures.createConquestVictoryFixture],
  ['score-timer-victory-fixture', fixtures.createScoreTimerVictoryFixture],
  ['score-timer-draw-fixture', fixtures.createScoreTimerDrawFixture],
  ['score-timer-defeat-fixture', fixtures.createScoreTimerDefeatFixture],
  ['conquest-defeat-fixture', fixtures.createConquestDefeatFixture],
  ['blocking-rules-fixture', fixtures.createBlockingRulesFixture],
  ['unit-sharing-fixture', fixtures.createUnitSharingFixture],
  ['feudal-missing-prereq-fixture', fixtures.createFeudalMissingPrereqFixture],
  ['feudal-age-fixture', fixtures.createFeudalAgeFixture],
  ['feudal-blacksmith-fixture', fixtures.createFeudalBlacksmithFixture],
  ['feudal-stable-fixture', fixtures.createFeudalStableFixture],
  ['blocked-stable-spawn-fixture', fixtures.createBlockedStableSpawnFixture],
  ['isolated-scout-spawn-fixture', fixtures.createIsolatedScoutSpawnFixture],
  ['castle-age-fixture', fixtures.createCastleAgeFixture],
  ['castle-town-center-fixture', fixtures.createCastleTownCenterFixture],
  ['multi-villager-construction-fixture', fixtures.createMultiVillagerConstructionFixture],
  ['auto-mine-camp-fixture', fixtures.createAutoMineCampFixture],
  ['repair-fixture', fixtures.createRepairFixture],
  ['single-villager-construction-fixture', fixtures.createSingleVillagerConstructionFixture],
  ['castle-upgrades-fixture', fixtures.createCastleUpgradesFixture],
  ['imperial-upgrades-fixture', fixtures.createImperialUpgradesFixture],
  ['imperial-age-fixture', fixtures.createImperialAgeFixture],
  ['imperial-missing-prereq-fixture', fixtures.createImperialMissingPrereqFixture],
  ['imperial-arbalest-fixture', fixtures.createImperialArbalestFixture],
  ['imperial-halberdier-fixture', fixtures.createImperialHalberdierFixture],
  ['pikeman-vs-knight-fixture', fixtures.createPikemanVsKnightFixture],
  ['halberdier-vs-knight-fixture', fixtures.createHalberdierVsKnightFixture],
  ['imperial-stable-fixture', fixtures.createImperialStableFixture],
  ['camel-vs-hussar-fixture', fixtures.createCamelVsHussarFixture],
  ['halberdier-vs-cavalier-fixture', fixtures.createHalberdierVsCavalierFixture],
  ['imperial-castle-britons-fixture', fixtures.createImperialCastleBritonsFixture],
  ['imperial-castle-franks-fixture', fixtures.createImperialCastleFranksFixture],
  ['camel-vs-cavalry-fixture', fixtures.createCamelVsCavalryFixture],
  ['spearman-vs-camel-fixture', fixtures.createSpearmanVsCamelFixture],
  ['cavalry-archer-ranged-fixture', fixtures.createCavalryArcherRangedFixture],
  ['skirmisher-vs-cavalry-archer-fixture', fixtures.createSkirmisherVsCavalryArcherFixture],
  ['siege-workshop-fixture', fixtures.createSiegeWorkshopFixture],
  ['imperial-siege-fixture', fixtures.createImperialSiegeFixture],
  ['imperial-blacksmith-fixture', fixtures.createImperialBlacksmithFixture],
  ['blacksmith-progression-fixture', fixtures.createBlacksmithProgressionFixture],
  ['double-blacksmith-race-fixture', fixtures.createDoubleBlacksmithRaceFixture],
  ['champion-vs-halberdier-fixture', fixtures.createChampionVsHalberdierFixture],
  ['champion-vs-armored-halberdier-fixture', fixtures.createChampionVsArmoredHalberdierFixture],
  ['militia-line-fixture', fixtures.createMilitiaLineFixture],
  ['paladin-fixture', fixtures.createPaladinFixture],
  ['heavy-camel-vs-knight-fixture', fixtures.createHeavyCamelVsKnightFixture],
  ['fu3-castle-no-archers-fixture', fixtures.createFu3CastleNoArchersFixture],
  ['fu3-castle-three-archers-fixture', fixtures.createFu3CastleThreeArchersFixture],
  ['fu3-castle-five-archers-fixture', fixtures.createFu3CastleFiveArchersFixture],
  ['fu3-castle-edge-range-fixture', fixtures.createFu3CastleEdgeRangeFixture],
  ['fu3-stone-wall-fixture', fixtures.createFu3StoneWallFixture],
  ['fu3-stone-wall-blocking-fixture', fixtures.createFu3StoneWallBlockingFixture],
  ['fu3-stone-wall-combat-fixture', fixtures.createFu3StoneWallCombatFixture],
  ['fu3-palisade-wall-fixture', fixtures.createFu3PalisadeWallFixture],
  ['onager-min-range-blocked-fixture', fixtures.createOnagerMinRangeBlockedFixture],
  ['siege-ram-vs-building-fixture', fixtures.createSiegeRamVsBuildingFixture],
  ['bombard-cannon-vs-building-fixture', fixtures.createBombardCannonVsBuildingFixture],
  ['town-center-reselect-fixture', fixtures.createTownCenterReselectFixture],
  ['bombard-cannon-min-range-blocked-fixture', fixtures.createBombardCannonMinRangeBlockedFixture],
  ['imperial-castle-fixture', fixtures.createImperialCastleFixture],
  ['trebuchet-pack-fixture', fixtures.createTrebuchetPackFixture],
  ['trebuchet-vs-building-fixture', fixtures.createTrebuchetVsBuildingFixture],
  ['mangonel-ranged-fixture', fixtures.createMangonelRangedFixture],
  ['scorpion-ranged-fixture', fixtures.createScorpionRangedFixture],
  ['tower-vs-siege-priority-fixture', fixtures.createTowerVsSiegePriorityFixture],
  ['mangonel-vs-spearman-fixture', fixtures.createMangonelVsSpearmanFixture],
  ['mangonel-vs-clustered-infantry-fixture', fixtures.createMangonelVsClusteredInfantryFixture],
  ['mangonel-vs-building-splash-fixture', fixtures.createMangonelVsBuildingSplashFixture],
  ['mangonel-vs-knight-fixture', fixtures.createMangonelVsKnightFixture],
  ['mangonel-min-range-blocked-fixture', fixtures.createMangonelMinRangeBlockedFixture],
  ['mangonel-outside-min-range-fixture', fixtures.createMangonelOutsideMinRangeFixture],
  ['ram-vs-building-fixture', fixtures.createRamVsBuildingFixture],
  ['ram-vs-villager-fixture', fixtures.createRamVsVillagerFixture],
  ['pikeman-vs-ram-fixture', fixtures.createPikemanVsRamFixture],
  ['camel-vs-ram-fixture', fixtures.createCamelVsRamFixture],
  ['monastery-fixture', fixtures.createMonasteryFixture],
  ['monk-heal-fixture', fixtures.createMonkHealFixture],
  ['monk-convert-fixture', fixtures.createMonkConvertFixture],
  ['monk-convert-heresy-fixture', fixtures.createMonkConvertHeresyFixture],
  ['monk-convert-monk-fixture', fixtures.createMonkConvertMonkFixture],
  ['monk-convert-monk-atonement-fixture', fixtures.createMonkConvertMonkAtonementFixture],
  ['monk-fog-fixture', fixtures.createMonkFogFixture],
  ['monk-convert-vision-fixture', fixtures.createMonkConvertVisionFixture],
  ['monk-heal-over-convert-fixture', fixtures.createMonkHealOverConvertFixture],
  ['monk-healthy-friendly-with-enemy-fixture', fixtures.createMonkHealthyFriendlyWithEnemyFixture],
  ['monk-double-convert-fixture', fixtures.createMonkDoubleConvertFixture],
  ['monk-flip-flop-fixture', fixtures.createMonkFlipFlopFixture],
  ['monk-convert-cleanup-fixture', fixtures.createMonkConvertCleanupFixture],
  ['monk-relic-drop-fixture', fixtures.createMonkRelicDropFixture],
  ['monk-relic-drop-cramped-fixture', fixtures.createMonkRelicDropCrampedFixture],
  ['castle-unique-fixture', fixtures.createCastleUniqueFixture],
  ['castle-non-britons-fixture', fixtures.createCastleNonBritonsFixture],
  ['castle-defensive-fire-fixture', fixtures.createCastleDefensiveFireFixture],
  ['castle-ai-target-priority-fixture', fixtures.createCastleAiTargetPriorityFixture],
  ['longbowman-ranged-fixture', fixtures.createLongbowmanRangedFixture],
  ['loom-fixture', fixtures.createLoomFixture],
  ['tower-upgrade-baseline-fixture', fixtures.createTowerUpgradeBaselineFixture],
  ['tower-upgrade-guard-fixture', fixtures.createTowerUpgradeGuardFixture],
  ['tower-upgrade-edge-nokeep-fixture', fixtures.createTowerUpgradeEdgeNoKeepFixture],
  ['tower-upgrade-edge-keep-fixture', fixtures.createTowerUpgradeEdgeKeepFixture],
  ['tower-fletching-fixture', fixtures.createTowerFletchingFixture],
  ['monk-block-printing-baseline-fixture', fixtures.createMonkBlockPrintingBaselineFixture],
  ['monk-block-printing-fixture', fixtures.createMonkBlockPrintingFixture],
  ['monk-base-convert-range-fixture', fixtures.createMonkBaseConvertRangeFixture],
  ['monk-sanctity-baseline-fixture', fixtures.createMonkSanctityBaselineFixture],
  ['monk-sanctity-fixture', fixtures.createMonkSanctityFixture],
  ['monk-faith-baseline-fixture', fixtures.createMonkFaithBaselineFixture],
  ['monk-faith-rest-fixture', fixtures.createMonkFaithRestFixture],
  ['monk-faith-defended-fixture', fixtures.createMonkFaithDefendedFixture],
  ['siege-engineers-baseline-fixture', fixtures.createSiegeEngineersBaselineFixture],
  ['siege-engineers-researched-fixture', fixtures.createSiegeEngineersResearchedFixture],
  ['sappers-baseline-fixture', fixtures.createSappersBaselineFixture],
  ['sappers-researched-fixture', fixtures.createSappersResearchedFixture],
  ['bloodlines-baseline-fixture', fixtures.createBloodlinesBaselineFixture],
  ['bloodlines-researched-fixture', fixtures.createBloodlinesResearchedFixture],
  ['bloodlines-feudal-stable-fixture', fixtures.createBloodlinesFeudalStableFixture],
  ['husbandry-movement-baseline-fixture', fixtures.createHusbandryBaselineFixture],
  ['husbandry-movement-researched-fixture', fixtures.createHusbandryResearchedFixture],
  ['squires-movement-baseline-fixture', fixtures.createSquiresBaselineFixture],
  ['squires-movement-researched-fixture', fixtures.createSquiresResearchedFixture],
  ['los-techs-fixture', fixtures.createLosTechsFixture],
  ['conscription-fixture', fixtures.createConscriptionFixture],
  ['gate-fixture', fixtures.createGatesFixture],
  ['gate-built-in-match-fixture', fixtures.createGateBuiltInMatchFixture],
  ['unit-repair-fixture', fixtures.createUnitRepairFixture],
  ['transport-fixture', fixtures.createTransportFixture],
  ['murder-holes-hugged-fixture', fixtures.createMurderHolesHuggedFixture],
  ['murder-holes-researched-fixture', fixtures.createMurderHolesResearchedFixture],
  ['civ-shepherd-britons-fixture', fixtures.createCivShepherdBritonsFixture],
  ['civ-shepherd-control-fixture', fixtures.createCivShepherdControlFixture],
  ['civ-franks-knight-fixture', fixtures.createCivFranksKnightFixture],
  ['civ-franks-knight-control-fixture', fixtures.createCivFranksKnightControlFixture],
  ['civ-mongols-scout-fixture', fixtures.createCivMongolsScoutFixture],
  ['civ-mongols-scout-control-fixture', fixtures.createCivMongolsScoutControlFixture],
  ['civ-teutons-fixture', fixtures.createCivTeutonsFixture],
  ['civ-koreans-tower-fixture', fixtures.createCivKoreansTowerFixture],
  ['civ-goths-pop-fixture', fixtures.createCivGothsPopFixture],
  ['civ-khmer-house-fixture', fixtures.createCivKhmerHouseFixture],
  ['civ-incas-armor-fixture', fixtures.createCivIncasArmorFixture],
  ['ai-tribute-fixture', fixtures.createAiTributeFixture],
  ['ai-ferry-fixture', fixtures.createAiFerryFixture],
  ['ai-ferry-train-fixture', fixtures.createAiFerryTrainFixture],
  ['tower-arrows-fixture', fixtures.createTowerArrowsFixture],
  ['attack-ally-fixture', fixtures.createAttackAllyFixture],
  ['damage-showcase-fixture', fixtures.createDamageShowcaseFixture],
  ['redemption-buildings-fixture', fixtures.createRedemptionBuildingsFixture],
  ['redemption-buildings-baseline-fixture', fixtures.createRedemptionBuildingsBaselineFixture],
  ['civ-goths-infantry-fixture', fixtures.createCivGothsInfantryFixture],
  ['civ-goths-infantry-control-fixture', fixtures.createCivGothsInfantryControlFixture],
  ['civ-aztecs-train-fixture', fixtures.createCivAztecsTrainFixture],
  ['civ-aztecs-train-control-fixture', fixtures.createCivAztecsTrainControlFixture],
  ['civ-goths-cost-fixture', fixtures.createCivGothsCostFixture],
  ['civ-goths-cost-control-fixture', fixtures.createCivGothsCostControlFixture],
  ['villager-speed-baseline-fixture', fixtures.createVillagerSpeedBaselineFixture],
  ['villager-speed-wheelbarrow-fixture', fixtures.createVillagerSpeedWheelbarrowFixture],
  ['villager-speed-both-fixture', fixtures.createVillagerSpeedBothFixture],
  ['loom-broke-fixture', fixtures.createLoomBrokeFixture],
  ['loom-researched-fixture', fixtures.createLoomResearchedFixture],
  // M7 units-beyond-circles: a visual-only showcase placing one P1 unit per
  // render role (capture target for the unit-silhouette change).
  ['unit-showcase-fixture', fixtures.createUnitShowcaseFixture],
  ['vikings-regeneration-fixture', fixtures.createVikingsRegenerationFixture],
  ['trade-route-fixture', fixtures.createTradeRouteFixture],
  ['ai-trade-fixture', fixtures.createAiTradeFixture],
  ['naval-trade-fixture', fixtures.createNavalTradeFixture],
  ['missionary-fixture', fixtures.createMissionaryFixture],
  // M7 building-visuals: a visual-only showcase placing one P1 COMPLETED
  // building per render role (capture target for the building-silhouette change).
  ['building-showcase-fixture', fixtures.createBuildingShowcaseFixture],
  // Behind-building silhouette cue: one hidden + one control villager
  // (capture target for the unit-occlusion-outline change).
  ['occlusion-showcase-fixture', fixtures.createOcclusionShowcaseFixture],
  // M7 terrain-blending: a visual-only showcase painting adjacent terrain kinds
  // (capture target for the kind-to-kind transition change).
  ['terrain-showcase-fixture', fixtures.createTerrainShowcaseFixture],
  ['terrain-water-motion-fixture', fixtures.createTerrainWaterMotionFixture],
  // M7 combat/gather-feedback: a visual-only showcase with a selectable lone
  // villager (pulse) + an adjacent melee knot that auto-fights (hit flash).
  ['feedback-showcase-fixture', fixtures.createFeedbackShowcaseFixture],
  ['castle-fletching-fixture', fixtures.createCastleFletchingFixture],
  ['castle-garrison-fixture', fixtures.createCastleGarrisonFixture],
  ['garrison-heal-fixture', fixtures.createGarrisonHealFixture],
  ['garrison-heal-herbal-fixture', fixtures.createGarrisonHealHerbalFixture],
  ['monk-relic-fixture', fixtures.createMonkRelicFixture],
  ['wonder-imperial-fixture', fixtures.createWonderImperialFixture],
  ['wonder-existing-fixture', fixtures.createWonderExistingFixture],
  ['wonder-short-countdown-fixture', fixtures.createWonderShortCountdownFixture],
  ['two-wonder-tie-fixture', fixtures.createTwoWonderTieFixture],
  ['wonder-destroyed-fixture', fixtures.createWonderDestroyedFixture],
  ['relic-short-countdown-fixture', fixtures.createRelicShortCountdownFixture],
  ['relic-not-all-held-fixture', fixtures.createRelicNotAllHeldFixture],
  ['wonder-relic-tie-fixture', fixtures.createWonderRelicTieFixture],
  ['wonder-owner-after-conversion-fixture', fixtures.createWonderOwnerAfterConversionFixture],
  ['feudal-spearman-fixture', fixtures.createFeudalSpearmanFixture],
  ['feudal-skirmisher-fixture', fixtures.createFeudalSkirmisherFixture],
  ['militia-combat-fixture', fixtures.createMilitiaCombatFixture],
  ['moving-enemy-attack-fixture', fixtures.createMovingEnemyAttackFixture],
  ['auto-aggro-idle-militia-in-vision-fixture', fixtures.createAutoAggroIdleMilitiaInVisionFixture],
  ['auto-aggro-idle-militia-out-of-vision-fixture', fixtures.createAutoAggroIdleMilitiaOutOfVisionFixture],
  ['auto-aggro-archer-pursuit-fixture', fixtures.createAutoAggroArcherPursuitFixture],
  ['auto-aggro-player-move-overrides-fixture', fixtures.createAutoAggroPlayerMoveOverridesFixture],
  ['auto-aggro-villager-adjacent-fixture', fixtures.createAutoAggroVillagerAdjacentFixture],
  ['auto-aggro-villager-no-pursuit-fixture', fixtures.createAutoAggroVillagerNoPursuitFixture],
  ['auto-aggro-villager-gathering-fixture', fixtures.createAutoAggroVillagerGatheringFixture],
  ['auto-aggro-monk-skip-fixture', fixtures.createAutoAggroMonkSkipFixture],
  ['auto-aggro-sequential-targets-fixture', fixtures.createAutoAggroSequentialTargetsFixture],
  ['feudal-watch-tower-fixture', fixtures.createFeudalWatchTowerFixture],
  ['ai-rush-fixture', fixtures.createAiRushFixture],
  ['ai-planner-fixture', fixtures.createAiPlannerFixture],
  ['ai-scouting-response-fixture', fixtures.createAiScoutingResponseFixture],
  ['ai-feudal-stone-fixture', fixtures.createAiFeudalStoneFixture],
  ['new-unit-reach-fixture', fixtures.createNewUnitReachFixture],
  ['new-tech-reach-fixture', fixtures.createNewTechReachFixture],
  ['ai-versus-ai-fixture', fixtures.createAiVersusAiFixture],
  ['exhausted-resources-fixture', fixtures.createExhaustedResourcesFixture],
  ['shore-fishing-fixture', fixtures.createShoreFishingFixture],
  ['demolition-ship-fixture', fixtures.createDemolitionShipFixture],
  ['petard-fixture', fixtures.createPetardFixture],
  ['three-player-fixture', fixtures.createThreePlayerFixture],
  ['allied-three-player-fixture', fixtures.createAlliedThreePlayerFixture],
  ['ai-difficulty-fixture', fixtures.createAiDifficultyFixture],
  ['ai-monk-fixture', fixtures.createAiMonkFixture],
  ['ai-monk-heal-fixture', fixtures.createAiMonkHealFixture],
  ['ai-monk-relic-fixture', fixtures.createAiMonkRelicFixture],
  ['ai-wonder-fixture', fixtures.createAiWonderFixture],
  ['feudal-market-fixture', fixtures.createFeudalMarketFixture],
  ['town-center-defense-fixture', fixtures.createTownCenterDefenseFixture],
  ['mining-camp-fixture', fixtures.createMiningCampFixture],
  ['fish-fixture', fixtures.createFishFixture],
  ['heated-shot-fixture', fixtures.createHeatedShotFixture],
  ['heated-shot-researched-fixture', fixtures.createHeatedShotResearchedFixture],
  ['ai-castle-age-military-fixture', fixtures.createAiCastleAgeMilitaryFixture],
  ['queued-orders-fixture', fixtures.createQueuedOrdersFixture],
  ['university-fixture', fixtures.createUniversityFixture],
  ['university-imperial-fixture', fixtures.createUniversityImperialFixture],
  ['naval-fixture', fixtures.createNavalFixture],
  ['naval-castle-age-fixture', fixtures.createNavalCastleAgeFixture],
  ['naval-imperial-fixture', fixtures.createNavalImperialFixture],
  ['villager-no-wood-dropoff-fixture', fixtures.createVillagerNoWoodDropoffFixture],
  ['fog-memory-castle-edge-fixture', fixtures.createFogMemoryCastleEdgeFixture],
  ['fog-memory-castle-destroy-edge-fixture', fixtures.createFogMemoryCastleDestroyEdgeFixture],
  ['boar-aggro-fixture', fixtures.createBoarAggroFixture],
  ['boar-hunt-fixture', fixtures.createBoarHuntFixture],
  ['wolf-aggro-fixture', fixtures.createWolfAggroFixture],
  ['orders-fixture', fixtures.createOrdersFixture],
  ['ai-economy-fixture', fixtures.createAiEconomyFixture],
  ['ai-age-up-priority-fixture', fixtures.createAiAgeUpPriorityFixture],
  ['ai-villager-reserve-fixture', fixtures.createAiVillagerReserveFixture],
  ['ai-market-ageup-fixture', fixtures.createAiMarketAgeUpFixture],
  ['villager-selection-fixture', fixtures.createVillagerSelectionFixture],
  ['double-click-selection-fixture', fixtures.createDoubleClickSelectionFixture],
  ['mixed-selection-fixture', fixtures.createMixedSelectionFixture],
  ['tile-selection-cycle-fixture', fixtures.createTileSelectionCycleFixture],
  ['sheep-ownership-fixture', fixtures.createSheepOwnershipFixture],
  ['sheep-movement-fixture', fixtures.createSheepMovementFixture],
  ['sheep-vision-fixture', fixtures.createSheepVisionFixture],
  ['resource-depletion-fixture', fixtures.createResourceDepletionFixture],
  ['farm-depletion-fixture', fixtures.createFarmDepletionFixture],
  ['farm-reseed-fixture', fixtures.createFarmReseedFixture],
  ['farm-ownership-fixture', fixtures.createFarmOwnershipFixture],
  ['farm-upgrade-techs-fixture', fixtures.createFarmUpgradeTechsFixture],
  ['farm-upgrade-build-fixture', fixtures.createFarmUpgradeBuildFixture],
  ['farm-upgrade-reseed-fixture', fixtures.createFarmUpgradeReseedFixture],
  ['move-target-unblocks-fixture', fixtures.createMoveTargetUnblocksFixture],
  ['narrow-corridor-fixture', fixtures.createNarrowCorridorFixture],
  ['gather-unreachable-reroute-fixture', fixtures.createGatherUnreachableRerouteFixture],
  ['gather-island-food-fixture', fixtures.createGatherIslandFoodFixture],
  ['woodline-clearing-fixture', fixtures.createWoodlineClearingFixture],
  ['outpost-vision-fixture', fixtures.createOutpostVisionFixture],
  ['fish-trap-fixture', fixtures.createFishTrapFixture],
  ['ai-under-raid-fixture', fixtures.createAiUnderRaidFixture],
  ['dropoff-unreachable-reroute-fixture', fixtures.createDropOffUnreachableRerouteFixture],
  ['dropoff-convoy-fixture', fixtures.createDropOffConvoyFixture],
  ['fog-memory-fixture', fixtures.createFogMemoryFixture],
  ['building-footprint-vision-fixture', fixtures.createBuildingFootprintVisionFixture],
  // Slice 11: alternate playable maps. Both share the default
  // two-player layout; only terrain differs.
  ['black-forest-fixture', createBlackForestMap],
  ['black-forest', createBlackForestMap],
  ['arena-fixture', createArenaMap],
  ['arena', createArenaMap],
  // §5.4's roster: Arabia is the standard map's own character, so the name is
  // an alias for the default; the three scripts below shape the world their
  // own way and keep the standard opening.
  ['arabia', (seed: string) => createDefaultMap(seed)],
  ['coastal', createCoastalMap],
  ['fortress', createFortressMap],
  ['gold-rush', createGoldRushMap],
  ['nomad', createNomadMap],
  ['islands', createIslandsMap],
  // Slice 12 Task B: scenario-validation fixtures. Each seed exercises
  // one failure mode of the bridge-boot validation pass; the
  // `-ok-fixture` is the positive control.
  ['slice12-validation-ok-fixture', fixtures.createScenarioValidationFixture],
  ['slice12-validation-out-of-bounds-fixture', fixtures.createScenarioValidationFixture],
  ['slice12-validation-overlap-fixture', fixtures.createScenarioValidationFixture],
  ['slice12-validation-unit-in-building-fixture', fixtures.createScenarioValidationFixture],
  ['slice12-validation-resource-on-building-fixture', fixtures.createScenarioValidationFixture],
  ['slice12-validation-resource-on-resource-fixture', fixtures.createScenarioValidationFixture],
]);
