// Every scenario seed the game knows, and the factory that builds it. Split out
// of ./dispatch.ts, which had grown past the 500-line budget purely by holding
// this table: the dispatcher is a two-line lookup, and the table is a flat
// one-line-per-seed list that only ever grows. Keeping them apart means adding
// a fixture touches the list and nothing else.


import {
  createAiAgeUpPriorityFixture,
  createAiVillagerReserveFixture,
  createAiMarketAgeUpFixture,
  createAiDifficultyFixture,
  createAiEconomyFixture,
  createAiMonkFixture,
  createAiMonkHealFixture,
  createAiMonkRelicFixture,
  createAiPlannerFixture,
  createAiRushFixture,
  createAiScoutingResponseFixture,
  createAiWonderFixture,
  createAutoAggroArcherPursuitFixture,
  createAutoAggroIdleMilitiaInVisionFixture,
  createAutoAggroIdleMilitiaOutOfVisionFixture,
  createAutoAggroMonkSkipFixture,
  createAutoAggroPlayerMoveOverridesFixture,
  createAutoAggroSequentialTargetsFixture,
  createAutoAggroVillagerAdjacentFixture,
  createAutoAggroVillagerGatheringFixture,
  createAutoAggroVillagerNoPursuitFixture,
  createBlacksmithProgressionFixture,
  createBlockedStableSpawnFixture,
  createBlockingRulesFixture,
  createBoarAggroFixture,
  createBoarHuntFixture,
  createBombardCannonMinRangeBlockedFixture,
  createBombardCannonVsBuildingFixture,
  createTownCenterReselectFixture,
  createBuildingFootprintVisionFixture,
  createBuildingShowcaseFixture,
  createOcclusionShowcaseFixture,
  createCamelVsCavalryFixture,
  createCamelVsHussarFixture,
  createCamelVsRamFixture,
  createCastleAgeFixture,
  createCastleAiTargetPriorityFixture,
  createCastleDefensiveFireFixture,
  createCastleFletchingFixture,
  createCastleGarrisonFixture,
  createGarrisonHealFixture,
  createGarrisonHealHerbalFixture,
  createCastleNonBritonsFixture,
  createCastleTownCenterFixture,
  createCastleUniqueFixture,
  createCastleUpgradesFixture,
  createCavalryArcherRangedFixture,
  createChampionVsArmoredHalberdierFixture,
  createChampionVsHalberdierFixture,
  createConquestDefeatFixture,
  createConquestVictoryFixture,
  createDoubleBlacksmithRaceFixture,
  createDoubleClickSelectionFixture,
  createFarmDepletionFixture,
  createFarmOwnershipFixture,
  createFarmReseedFixture,
  createFarmUpgradeBuildFixture,
  createFarmUpgradeReseedFixture,
  createFarmUpgradeTechsFixture,
  createFeedbackShowcaseFixture,
  createFeudalAgeFixture,
  createFeudalBlacksmithFixture,
  createFeudalMarketFixture,
  createFeudalMissingPrereqFixture,
  createFeudalSkirmisherFixture,
  createFeudalSpearmanFixture,
  createFeudalStableFixture,
  createFeudalWatchTowerFixture,
  createFishFixture,
  createNavalCastleAgeFixture,
  createNavalFixture,
  createNavalImperialFixture,
  createAiCastleAgeMilitaryFixture,
  createHeatedShotFixture,
  createHeatedShotResearchedFixture,
  createUniversityFixture,
  createUniversityImperialFixture,
  createFogMemoryCastleDestroyEdgeFixture,
  createFogMemoryCastleEdgeFixture,
  createFogMemoryFixture,
  createFu3CastleEdgeRangeFixture,
  createFu3CastleFiveArchersFixture,
  createFu3CastleNoArchersFixture,
  createFu3CastleThreeArchersFixture,
  createFu3PalisadeWallFixture,
  createFu3StoneWallBlockingFixture,
  createFu3StoneWallCombatFixture,
  createFu3StoneWallFixture,
  createGatherUnreachableRerouteFixture,
  createDropOffUnreachableRerouteFixture,
  createHalberdierVsCavalierFixture,
  createHalberdierVsKnightFixture,
  createHeavyCamelVsKnightFixture,
  createImperialAgeFixture,
  createImperialArbalestFixture,
  createImperialBlacksmithFixture,
  createImperialCastleBritonsFixture,
  createImperialCastleFixture,
  createImperialCastleFranksFixture,
  createImperialHalberdierFixture,
  createImperialMissingPrereqFixture,
  createImperialSiegeFixture,
  createImperialStableFixture,
  createImperialUpgradesFixture,
  createIsolatedScoutSpawnFixture,
  createLongbowmanRangedFixture,
  createLoomBrokeFixture,
  createLoomFixture,
  createLoomResearchedFixture,
  createTowerUpgradeBaselineFixture,
  createTowerUpgradeGuardFixture,
  createTowerUpgradeEdgeNoKeepFixture,
  createTowerUpgradeEdgeKeepFixture,
  createTowerFletchingFixture,
  createMonkBlockPrintingBaselineFixture,
  createMonkBlockPrintingFixture,
  createMonkSanctityBaselineFixture,
  createMonkSanctityFixture,
  createMonkFaithBaselineFixture,
  createMonkFaithDefendedFixture,
  createSiegeEngineersBaselineFixture,
  createSiegeEngineersResearchedFixture,
  createSappersBaselineFixture,
  createSappersResearchedFixture,
  createBloodlinesBaselineFixture,
  createBloodlinesResearchedFixture,
  createBloodlinesFeudalStableFixture,
  createHusbandryBaselineFixture,
  createHusbandryResearchedFixture,
  createSquiresBaselineFixture,
  createSquiresResearchedFixture,
  createLosTechsFixture,
  createConscriptionFixture,
  createGatesFixture,
  createMurderHolesHuggedFixture,
  createMurderHolesResearchedFixture,
  createCivShepherdBritonsFixture,
  createCivShepherdControlFixture,
  createCivFranksKnightFixture,
  createCivFranksKnightControlFixture,
  createCivMongolsScoutFixture,
  createCivMongolsScoutControlFixture,
  createCivGothsInfantryFixture,
  createCivGothsInfantryControlFixture,
  createCivAztecsTrainFixture,
  createCivAztecsTrainControlFixture,
  createCivGothsCostFixture,
  createCivGothsCostControlFixture,
  createVillagerSpeedBaselineFixture,
  createVillagerSpeedWheelbarrowFixture,
  createVillagerSpeedBothFixture,
  createMangonelMinRangeBlockedFixture,
  createMangonelOutsideMinRangeFixture,
  createMangonelRangedFixture,
  createMangonelVsClusteredInfantryFixture,
  createMangonelVsBuildingSplashFixture,
  createMangonelVsKnightFixture,
  createMangonelVsSpearmanFixture,
  createMilitiaCombatFixture,
  createMilitiaLineFixture,
  createMiningCampFixture,
  createMixedSelectionFixture,
  createMonasteryFixture,
  createMonkConvertCleanupFixture,
  createMonkConvertFixture,
  createMonkConvertHeresyFixture,
  createMonkConvertMonkFixture,
  createMonkConvertMonkAtonementFixture,
  createMonkConvertVisionFixture,
  createMonkDoubleConvertFixture,
  createMonkFlipFlopFixture,
  createMonkFogFixture,
  createMonkHealFixture,
  createMonkHealOverConvertFixture,
  createMonkHealthyFriendlyWithEnemyFixture,
  createMonkRelicDropCrampedFixture,
  createMonkRelicDropFixture,
  createMonkRelicFixture,
  createMoveTargetUnblocksFixture,
  createMovingEnemyAttackFixture,
  createAutoMineCampFixture,
  createMultiVillagerConstructionFixture,
  createRepairFixture,
  createSingleVillagerConstructionFixture,
  createNarrowCorridorFixture,
  createOnagerMinRangeBlockedFixture,
  createOrdersFixture,
  createPaladinFixture,
  createPikemanVsKnightFixture,
  createPikemanVsRamFixture,
  createRamVsBuildingFixture,
  createRamVsVillagerFixture,
  createRelicNotAllHeldFixture,
  createRelicShortCountdownFixture,
  createResourceDepletionFixture,
  createScenarioValidationFixture,
  createScoreTimerDefeatFixture,
  createScoreTimerDrawFixture,
  createScoreTimerVictoryFixture,
  createScorpionRangedFixture,
  createSheepMovementFixture,
  createSheepOwnershipFixture,
  createSheepVisionFixture,
  createSiegeRamVsBuildingFixture,
  createSiegeWorkshopFixture,
  createSkirmisherVsCavalryArcherFixture,
  createSpearmanVsCamelFixture,
  createTileSelectionCycleFixture,
  createTowerVsSiegePriorityFixture,
  createTownCenterDefenseFixture,
  createTrebuchetPackFixture,
  createTrebuchetVsBuildingFixture,
  createTerrainShowcaseFixture,
  createTerrainWaterMotionFixture,
  createUnitShowcaseFixture,
  createUnitSharingFixture,
  createVillagerNoWoodDropoffFixture,
  createVillagerSelectionFixture,
  createWolfAggroFixture,
  createWonderDestroyedFixture,
  createWonderExistingFixture,
  createWonderImperialFixture,
  createWonderOwnerAfterConversionFixture,
  createWonderRelicTieFixture,
  createWonderShortCountdownFixture,
  createTwoWonderTieFixture,
} from '../fixtures';
import { createArenaMap } from '../mapGeneration/arenaMap';
import { createBlackForestMap } from '../mapGeneration/blackForestMap';
import type { PrototypeScenario } from '../prototypeScenario';

type ScenarioFactory = (seed: string) => PrototypeScenario;

export const SCENARIO_FACTORIES: ReadonlyMap<string, ScenarioFactory>
  = new Map<string, ScenarioFactory>([
  ['conquest-victory-fixture', createConquestVictoryFixture],
  ['score-timer-victory-fixture', createScoreTimerVictoryFixture],
  ['score-timer-draw-fixture', createScoreTimerDrawFixture],
  ['score-timer-defeat-fixture', createScoreTimerDefeatFixture],
  ['conquest-defeat-fixture', createConquestDefeatFixture],
  ['blocking-rules-fixture', createBlockingRulesFixture],
  ['unit-sharing-fixture', createUnitSharingFixture],
  ['feudal-missing-prereq-fixture', createFeudalMissingPrereqFixture],
  ['feudal-age-fixture', createFeudalAgeFixture],
  ['feudal-blacksmith-fixture', createFeudalBlacksmithFixture],
  ['feudal-stable-fixture', createFeudalStableFixture],
  ['blocked-stable-spawn-fixture', createBlockedStableSpawnFixture],
  ['isolated-scout-spawn-fixture', createIsolatedScoutSpawnFixture],
  ['castle-age-fixture', createCastleAgeFixture],
  ['castle-town-center-fixture', createCastleTownCenterFixture],
  ['multi-villager-construction-fixture', createMultiVillagerConstructionFixture],
  ['auto-mine-camp-fixture', createAutoMineCampFixture],
  ['repair-fixture', createRepairFixture],
  ['single-villager-construction-fixture', createSingleVillagerConstructionFixture],
  ['castle-upgrades-fixture', createCastleUpgradesFixture],
  ['imperial-upgrades-fixture', createImperialUpgradesFixture],
  ['imperial-age-fixture', createImperialAgeFixture],
  ['imperial-missing-prereq-fixture', createImperialMissingPrereqFixture],
  ['imperial-arbalest-fixture', createImperialArbalestFixture],
  ['imperial-halberdier-fixture', createImperialHalberdierFixture],
  ['pikeman-vs-knight-fixture', createPikemanVsKnightFixture],
  ['halberdier-vs-knight-fixture', createHalberdierVsKnightFixture],
  ['imperial-stable-fixture', createImperialStableFixture],
  ['camel-vs-hussar-fixture', createCamelVsHussarFixture],
  ['halberdier-vs-cavalier-fixture', createHalberdierVsCavalierFixture],
  ['imperial-castle-britons-fixture', createImperialCastleBritonsFixture],
  ['imperial-castle-franks-fixture', createImperialCastleFranksFixture],
  ['camel-vs-cavalry-fixture', createCamelVsCavalryFixture],
  ['spearman-vs-camel-fixture', createSpearmanVsCamelFixture],
  ['cavalry-archer-ranged-fixture', createCavalryArcherRangedFixture],
  ['skirmisher-vs-cavalry-archer-fixture', createSkirmisherVsCavalryArcherFixture],
  ['siege-workshop-fixture', createSiegeWorkshopFixture],
  ['imperial-siege-fixture', createImperialSiegeFixture],
  ['imperial-blacksmith-fixture', createImperialBlacksmithFixture],
  ['blacksmith-progression-fixture', createBlacksmithProgressionFixture],
  ['double-blacksmith-race-fixture', createDoubleBlacksmithRaceFixture],
  ['champion-vs-halberdier-fixture', createChampionVsHalberdierFixture],
  ['champion-vs-armored-halberdier-fixture', createChampionVsArmoredHalberdierFixture],
  ['militia-line-fixture', createMilitiaLineFixture],
  ['paladin-fixture', createPaladinFixture],
  ['heavy-camel-vs-knight-fixture', createHeavyCamelVsKnightFixture],
  ['fu3-castle-no-archers-fixture', createFu3CastleNoArchersFixture],
  ['fu3-castle-three-archers-fixture', createFu3CastleThreeArchersFixture],
  ['fu3-castle-five-archers-fixture', createFu3CastleFiveArchersFixture],
  ['fu3-castle-edge-range-fixture', createFu3CastleEdgeRangeFixture],
  ['fu3-stone-wall-fixture', createFu3StoneWallFixture],
  ['fu3-stone-wall-blocking-fixture', createFu3StoneWallBlockingFixture],
  ['fu3-stone-wall-combat-fixture', createFu3StoneWallCombatFixture],
  ['fu3-palisade-wall-fixture', createFu3PalisadeWallFixture],
  ['onager-min-range-blocked-fixture', createOnagerMinRangeBlockedFixture],
  ['siege-ram-vs-building-fixture', createSiegeRamVsBuildingFixture],
  ['bombard-cannon-vs-building-fixture', createBombardCannonVsBuildingFixture],
  ['town-center-reselect-fixture', createTownCenterReselectFixture],
  ['bombard-cannon-min-range-blocked-fixture', createBombardCannonMinRangeBlockedFixture],
  ['imperial-castle-fixture', createImperialCastleFixture],
  ['trebuchet-pack-fixture', createTrebuchetPackFixture],
  ['trebuchet-vs-building-fixture', createTrebuchetVsBuildingFixture],
  ['mangonel-ranged-fixture', createMangonelRangedFixture],
  ['scorpion-ranged-fixture', createScorpionRangedFixture],
  ['tower-vs-siege-priority-fixture', createTowerVsSiegePriorityFixture],
  ['mangonel-vs-spearman-fixture', createMangonelVsSpearmanFixture],
  ['mangonel-vs-clustered-infantry-fixture', createMangonelVsClusteredInfantryFixture],
  ['mangonel-vs-building-splash-fixture', createMangonelVsBuildingSplashFixture],
  ['mangonel-vs-knight-fixture', createMangonelVsKnightFixture],
  ['mangonel-min-range-blocked-fixture', createMangonelMinRangeBlockedFixture],
  ['mangonel-outside-min-range-fixture', createMangonelOutsideMinRangeFixture],
  ['ram-vs-building-fixture', createRamVsBuildingFixture],
  ['ram-vs-villager-fixture', createRamVsVillagerFixture],
  ['pikeman-vs-ram-fixture', createPikemanVsRamFixture],
  ['camel-vs-ram-fixture', createCamelVsRamFixture],
  ['monastery-fixture', createMonasteryFixture],
  ['monk-heal-fixture', createMonkHealFixture],
  ['monk-convert-fixture', createMonkConvertFixture],
  ['monk-convert-heresy-fixture', createMonkConvertHeresyFixture],
  ['monk-convert-monk-fixture', createMonkConvertMonkFixture],
  ['monk-convert-monk-atonement-fixture', createMonkConvertMonkAtonementFixture],
  ['monk-fog-fixture', createMonkFogFixture],
  ['monk-convert-vision-fixture', createMonkConvertVisionFixture],
  ['monk-heal-over-convert-fixture', createMonkHealOverConvertFixture],
  ['monk-healthy-friendly-with-enemy-fixture', createMonkHealthyFriendlyWithEnemyFixture],
  ['monk-double-convert-fixture', createMonkDoubleConvertFixture],
  ['monk-flip-flop-fixture', createMonkFlipFlopFixture],
  ['monk-convert-cleanup-fixture', createMonkConvertCleanupFixture],
  ['monk-relic-drop-fixture', createMonkRelicDropFixture],
  ['monk-relic-drop-cramped-fixture', createMonkRelicDropCrampedFixture],
  ['castle-unique-fixture', createCastleUniqueFixture],
  ['castle-non-britons-fixture', createCastleNonBritonsFixture],
  ['castle-defensive-fire-fixture', createCastleDefensiveFireFixture],
  ['castle-ai-target-priority-fixture', createCastleAiTargetPriorityFixture],
  ['longbowman-ranged-fixture', createLongbowmanRangedFixture],
  ['loom-fixture', createLoomFixture],
  ['tower-upgrade-baseline-fixture', createTowerUpgradeBaselineFixture],
  ['tower-upgrade-guard-fixture', createTowerUpgradeGuardFixture],
  ['tower-upgrade-edge-nokeep-fixture', createTowerUpgradeEdgeNoKeepFixture],
  ['tower-upgrade-edge-keep-fixture', createTowerUpgradeEdgeKeepFixture],
  ['tower-fletching-fixture', createTowerFletchingFixture],
  ['monk-block-printing-baseline-fixture', createMonkBlockPrintingBaselineFixture],
  ['monk-block-printing-fixture', createMonkBlockPrintingFixture],
  ['monk-sanctity-baseline-fixture', createMonkSanctityBaselineFixture],
  ['monk-sanctity-fixture', createMonkSanctityFixture],
  ['monk-faith-baseline-fixture', createMonkFaithBaselineFixture],
  ['monk-faith-defended-fixture', createMonkFaithDefendedFixture],
  ['siege-engineers-baseline-fixture', createSiegeEngineersBaselineFixture],
  ['siege-engineers-researched-fixture', createSiegeEngineersResearchedFixture],
  ['sappers-baseline-fixture', createSappersBaselineFixture],
  ['sappers-researched-fixture', createSappersResearchedFixture],
  ['bloodlines-baseline-fixture', createBloodlinesBaselineFixture],
  ['bloodlines-researched-fixture', createBloodlinesResearchedFixture],
  ['bloodlines-feudal-stable-fixture', createBloodlinesFeudalStableFixture],
  ['husbandry-movement-baseline-fixture', createHusbandryBaselineFixture],
  ['husbandry-movement-researched-fixture', createHusbandryResearchedFixture],
  ['squires-movement-baseline-fixture', createSquiresBaselineFixture],
  ['squires-movement-researched-fixture', createSquiresResearchedFixture],
  ['los-techs-fixture', createLosTechsFixture],
  ['conscription-fixture', createConscriptionFixture],
  ['gate-fixture', createGatesFixture],
  ['murder-holes-hugged-fixture', createMurderHolesHuggedFixture],
  ['murder-holes-researched-fixture', createMurderHolesResearchedFixture],
  ['civ-shepherd-britons-fixture', createCivShepherdBritonsFixture],
  ['civ-shepherd-control-fixture', createCivShepherdControlFixture],
  ['civ-franks-knight-fixture', createCivFranksKnightFixture],
  ['civ-franks-knight-control-fixture', createCivFranksKnightControlFixture],
  ['civ-mongols-scout-fixture', createCivMongolsScoutFixture],
  ['civ-mongols-scout-control-fixture', createCivMongolsScoutControlFixture],
  ['civ-goths-infantry-fixture', createCivGothsInfantryFixture],
  ['civ-goths-infantry-control-fixture', createCivGothsInfantryControlFixture],
  ['civ-aztecs-train-fixture', createCivAztecsTrainFixture],
  ['civ-aztecs-train-control-fixture', createCivAztecsTrainControlFixture],
  ['civ-goths-cost-fixture', createCivGothsCostFixture],
  ['civ-goths-cost-control-fixture', createCivGothsCostControlFixture],
  ['villager-speed-baseline-fixture', createVillagerSpeedBaselineFixture],
  ['villager-speed-wheelbarrow-fixture', createVillagerSpeedWheelbarrowFixture],
  ['villager-speed-both-fixture', createVillagerSpeedBothFixture],
  ['loom-broke-fixture', createLoomBrokeFixture],
  ['loom-researched-fixture', createLoomResearchedFixture],
  // M7 units-beyond-circles: a visual-only showcase placing one P1 unit per
  // render role (capture target for the unit-silhouette change).
  ['unit-showcase-fixture', createUnitShowcaseFixture],
  // M7 building-visuals: a visual-only showcase placing one P1 COMPLETED
  // building per render role (capture target for the building-silhouette change).
  ['building-showcase-fixture', createBuildingShowcaseFixture],
  // Behind-building silhouette cue: one hidden + one control villager
  // (capture target for the unit-occlusion-outline change).
  ['occlusion-showcase-fixture', createOcclusionShowcaseFixture],
  // M7 terrain-blending: a visual-only showcase painting adjacent terrain kinds
  // (capture target for the kind-to-kind transition change).
  ['terrain-showcase-fixture', createTerrainShowcaseFixture],
  ['terrain-water-motion-fixture', createTerrainWaterMotionFixture],
  // M7 combat/gather-feedback: a visual-only showcase with a selectable lone
  // villager (pulse) + an adjacent melee knot that auto-fights (hit flash).
  ['feedback-showcase-fixture', createFeedbackShowcaseFixture],
  ['castle-fletching-fixture', createCastleFletchingFixture],
  ['castle-garrison-fixture', createCastleGarrisonFixture],
  ['garrison-heal-fixture', createGarrisonHealFixture],
  ['garrison-heal-herbal-fixture', createGarrisonHealHerbalFixture],
  ['monk-relic-fixture', createMonkRelicFixture],
  ['wonder-imperial-fixture', createWonderImperialFixture],
  ['wonder-existing-fixture', createWonderExistingFixture],
  ['wonder-short-countdown-fixture', createWonderShortCountdownFixture],
  ['two-wonder-tie-fixture', createTwoWonderTieFixture],
  ['wonder-destroyed-fixture', createWonderDestroyedFixture],
  ['relic-short-countdown-fixture', createRelicShortCountdownFixture],
  ['relic-not-all-held-fixture', createRelicNotAllHeldFixture],
  ['wonder-relic-tie-fixture', createWonderRelicTieFixture],
  ['wonder-owner-after-conversion-fixture', createWonderOwnerAfterConversionFixture],
  ['feudal-spearman-fixture', createFeudalSpearmanFixture],
  ['feudal-skirmisher-fixture', createFeudalSkirmisherFixture],
  ['militia-combat-fixture', createMilitiaCombatFixture],
  ['moving-enemy-attack-fixture', createMovingEnemyAttackFixture],
  ['auto-aggro-idle-militia-in-vision-fixture', createAutoAggroIdleMilitiaInVisionFixture],
  ['auto-aggro-idle-militia-out-of-vision-fixture', createAutoAggroIdleMilitiaOutOfVisionFixture],
  ['auto-aggro-archer-pursuit-fixture', createAutoAggroArcherPursuitFixture],
  ['auto-aggro-player-move-overrides-fixture', createAutoAggroPlayerMoveOverridesFixture],
  ['auto-aggro-villager-adjacent-fixture', createAutoAggroVillagerAdjacentFixture],
  ['auto-aggro-villager-no-pursuit-fixture', createAutoAggroVillagerNoPursuitFixture],
  ['auto-aggro-villager-gathering-fixture', createAutoAggroVillagerGatheringFixture],
  ['auto-aggro-monk-skip-fixture', createAutoAggroMonkSkipFixture],
  ['auto-aggro-sequential-targets-fixture', createAutoAggroSequentialTargetsFixture],
  ['feudal-watch-tower-fixture', createFeudalWatchTowerFixture],
  ['ai-rush-fixture', createAiRushFixture],
  ['ai-planner-fixture', createAiPlannerFixture],
  ['ai-scouting-response-fixture', createAiScoutingResponseFixture],
  ['ai-difficulty-fixture', createAiDifficultyFixture],
  ['ai-monk-fixture', createAiMonkFixture],
  ['ai-monk-heal-fixture', createAiMonkHealFixture],
  ['ai-monk-relic-fixture', createAiMonkRelicFixture],
  ['ai-wonder-fixture', createAiWonderFixture],
  ['feudal-market-fixture', createFeudalMarketFixture],
  ['town-center-defense-fixture', createTownCenterDefenseFixture],
  ['mining-camp-fixture', createMiningCampFixture],
  ['fish-fixture', createFishFixture],
  ['heated-shot-fixture', createHeatedShotFixture],
  ['heated-shot-researched-fixture', createHeatedShotResearchedFixture],
  ['ai-castle-age-military-fixture', createAiCastleAgeMilitaryFixture],
  ['university-fixture', createUniversityFixture],
  ['university-imperial-fixture', createUniversityImperialFixture],
  ['naval-fixture', createNavalFixture],
  ['naval-castle-age-fixture', createNavalCastleAgeFixture],
  ['naval-imperial-fixture', createNavalImperialFixture],
  ['villager-no-wood-dropoff-fixture', createVillagerNoWoodDropoffFixture],
  ['fog-memory-castle-edge-fixture', createFogMemoryCastleEdgeFixture],
  ['fog-memory-castle-destroy-edge-fixture', createFogMemoryCastleDestroyEdgeFixture],
  ['boar-aggro-fixture', createBoarAggroFixture],
  ['boar-hunt-fixture', createBoarHuntFixture],
  ['wolf-aggro-fixture', createWolfAggroFixture],
  ['orders-fixture', createOrdersFixture],
  ['ai-economy-fixture', createAiEconomyFixture],
  ['ai-age-up-priority-fixture', createAiAgeUpPriorityFixture],
  ['ai-villager-reserve-fixture', createAiVillagerReserveFixture],
  ['ai-market-ageup-fixture', createAiMarketAgeUpFixture],
  ['villager-selection-fixture', createVillagerSelectionFixture],
  ['double-click-selection-fixture', createDoubleClickSelectionFixture],
  ['mixed-selection-fixture', createMixedSelectionFixture],
  ['tile-selection-cycle-fixture', createTileSelectionCycleFixture],
  ['sheep-ownership-fixture', createSheepOwnershipFixture],
  ['sheep-movement-fixture', createSheepMovementFixture],
  ['sheep-vision-fixture', createSheepVisionFixture],
  ['resource-depletion-fixture', createResourceDepletionFixture],
  ['farm-depletion-fixture', createFarmDepletionFixture],
  ['farm-reseed-fixture', createFarmReseedFixture],
  ['farm-ownership-fixture', createFarmOwnershipFixture],
  ['farm-upgrade-techs-fixture', createFarmUpgradeTechsFixture],
  ['farm-upgrade-build-fixture', createFarmUpgradeBuildFixture],
  ['farm-upgrade-reseed-fixture', createFarmUpgradeReseedFixture],
  ['move-target-unblocks-fixture', createMoveTargetUnblocksFixture],
  ['narrow-corridor-fixture', createNarrowCorridorFixture],
  ['gather-unreachable-reroute-fixture', createGatherUnreachableRerouteFixture],
  ['dropoff-unreachable-reroute-fixture', createDropOffUnreachableRerouteFixture],
  ['fog-memory-fixture', createFogMemoryFixture],
  ['building-footprint-vision-fixture', createBuildingFootprintVisionFixture],
  // Slice 11: alternate playable maps. Both share the default
  // two-player layout; only terrain differs.
  ['black-forest-fixture', createBlackForestMap],
  ['black-forest', createBlackForestMap],
  ['arena-fixture', createArenaMap],
  ['arena', createArenaMap],
  // Slice 12 Task B: scenario-validation fixtures. Each seed exercises
  // one failure mode of the bridge-boot validation pass; the
  // `-ok-fixture` is the positive control.
  ['slice12-validation-ok-fixture', createScenarioValidationFixture],
  ['slice12-validation-out-of-bounds-fixture', createScenarioValidationFixture],
  ['slice12-validation-overlap-fixture', createScenarioValidationFixture],
  ['slice12-validation-unit-in-building-fixture', createScenarioValidationFixture],
  ['slice12-validation-resource-on-building-fixture', createScenarioValidationFixture],
  ['slice12-validation-resource-on-resource-fixture', createScenarioValidationFixture],
]);
