// Training costs, split out of prototypeEconomyRules.ts for the 500-LOC budget
// (2026-09-05). The table is the sim's own answer to "what can be trained",
// so the coverage census (spec §15.8) reads its universe from here.

import type { PlayerResources, TrainableUnitType } from './types';

// Every row is units.csv's cost, and TRAINING_TIME_TICKS its training time x TPS;
// the CSV's costs and times are Definitive Edition's (sourced 2026-09-23, pinned
// in the CSV's header). tests/content/trainAndResearchCostsAndTimes.test.ts holds
// every row to it, so no comment here restates a value.
export const TRAINING_COSTS: Record<TrainableUnitType, Partial<PlayerResources>> = {
  villager: { food: 50 },
  scout: { food: 80 },
  militia: { food: 50, gold: 20 },
  spearman: { food: 35, wood: 25 },
  archer: { wood: 25, gold: 45 },
  skirmisher: { food: 25, wood: 35 },
  'elite-skirmisher': { food: 25, wood: 35 },
  'eagle-warrior': { food: 20, gold: 50 },
  'elite-eagle-warrior': { food: 20, gold: 50 }, // the Elite upgrade is the whole cost
  'hand-cannoneer': { food: 45, gold: 50 },
  knight: { food: 60, gold: 75 },
  crossbowman: { wood: 25, gold: 45 },
  pikeman: { food: 35, wood: 25 },
  'light-cavalry': { food: 80 },
  camel: { food: 55, gold: 60 },
  'cavalry-archer': { wood: 40, gold: 60 },
  mangonel: { wood: 160, gold: 135 },
  scorpion: { wood: 75, gold: 75 },
  'battering-ram': { wood: 160, gold: 75 },
  monk: { gold: 100 },
  longbowman: { wood: 35, gold: 40 },
  arbalest: { wood: 25, gold: 45 },
  halberdier: { food: 35, wood: 25 },
  hussar: { food: 80 },
  'heavy-cavalry-archer': { wood: 40, gold: 60 },
  cavalier: { food: 60, gold: 75 },
  champion: { food: 50, gold: 20 },
  'elite-longbowman': { wood: 35, gold: 40 },
  onager: { wood: 160, gold: 135 },
  'siege-onager': { wood: 160, gold: 135 },
  'heavy-scorpion': { wood: 75, gold: 75 },
  'siege-ram': { wood: 160, gold: 75 },
  'capped-ram': { wood: 160, gold: 75 },
  'bombard-cannon': { wood: 225, gold: 225 },
  trebuchet: { wood: 200, gold: 200 },
  // The Petard, demolition infantry: cheap, and spent in one use.
  petard: { food: 65, gold: 20 },
  'trade-cart': { wood: 100, gold: 50 },
  'trade-cog': { wood: 100, gold: 50 },
  missionary: { food: 30, gold: 100 },
  // M5 naval.
  'fishing-ship': { wood: 75 },
  'transport-ship': { wood: 125 },
  'galley': { wood: 90, gold: 30 },
  'war-galley': { wood: 90, gold: 30 },
  'galleon': { wood: 90, gold: 30 },
  'fire-ship': { wood: 75, gold: 45 },
  'fast-fire-ship': { wood: 75, gold: 45 },
  'demolition-ship': { wood: 45, gold: 80 },
  'heavy-demolition-ship': { wood: 45, gold: 80 },
  'cannon-galleon': { wood: 200, gold: 150 },
  'elite-cannon-galleon': { wood: 200, gold: 150 },
  'jaguar-warrior': { food: 60, gold: 30 },
  'cataphract': { food: 70, gold: 75 },
  'woad-raider': { food: 70, gold: 25 },
  'chu-ko-nu': { wood: 40, gold: 35 },
  'throwing-axeman': { food: 55, gold: 25 },
  huskarl: { food: 75, gold: 35 },
  'tarkan': { food: 60, gold: 60 },
  samurai: { food: 45, gold: 30 },
  'war-wagon': { wood: 200, gold: 60 },
  'plumed-archer': { wood: 55, gold: 55 },
  'mangudai': { wood: 55, gold: 65 },
  'war-elephant': { food: 170, gold: 85 },
  'mameluke': { food: 55, gold: 85 },
  conquistador: { food: 75, gold: 60 },
  'teutonic-knight': { food: 85, gold: 30 },
  'janissary': { food: 60, gold: 55 },
  berserk: { food: 65, gold: 20 },
  'turtle-ship': { wood: 190, gold: 130 },
  longboat: { wood: 100, gold: 50 },
  'elite-jaguar-warrior': { food: 60, gold: 30 },
  'elite-cataphract': { food: 70, gold: 75 },
  'elite-woad-raider': { food: 70, gold: 25 },
  'elite-chu-ko-nu': { wood: 40, gold: 35 },
  'elite-throwing-axeman': { food: 55, gold: 25 },
  'elite-huskarl': { food: 75, gold: 35 },
  'elite-tarkan': { food: 60, gold: 60 },
  'elite-samurai': { food: 45, gold: 30 },
  'elite-war-wagon': { wood: 200, gold: 60 },
  'elite-plumed-archer': { wood: 55, gold: 55 },
  'elite-mangudai': { wood: 55, gold: 65 },
  'elite-war-elephant': { food: 170, gold: 85 },
  'elite-mameluke': { food: 55, gold: 85 },
  'elite-conquistador': { food: 75, gold: 60 },
  'elite-teutonic-knight': { food: 85, gold: 30 },
  'elite-janissary': { food: 60, gold: 55 },
  'elite-berserk': { food: 65, gold: 20 },
  'elite-turtle-ship': { wood: 190, gold: 130 },
  'elite-longboat': { wood: 100, gold: 50 },
  'man-at-arms': { food: 50, gold: 20 },
  'long-swordsman': { food: 50, gold: 20 },
  'two-handed-swordsman': { food: 50, gold: 20 },
  paladin: { food: 60, gold: 75 },
  'heavy-camel': { food: 55, gold: 60 },
};

/** Every trainable unit type, in table order — the universe the self-play
 *  coverage census reports its gap against. */
export const TRAINABLE_UNIT_TYPES: readonly TrainableUnitType[] =
  Object.keys(TRAINING_COSTS) as TrainableUnitType[];
