// Stat tables extracted from prototypeUnitRules.ts to keep that file
// under 500 LOC. Pure data + small constant helpers; the accessor
// functions stay in the parent file and read from these exports.

import type { UnitType } from '../unitTypes';

export interface WildlifeProfile {
  currentHp: number;
  maxHp: number;
  attackDamage: number;
  attackRange: number;
  reloadTicks: number;
  cooldownTicks: number;
  armor: number;
  // Mirrors CombatState.pierceArmorBonus (wildlife carry no armor techs → 0).
  pierceArmorBonus: number;
  autoAggro: boolean;
  isAlive: boolean;
  corpsePersists: boolean;
  aggroRange: number;
  targetEntityRef: null;
}

export interface UnitTintPalette {
  human: number;
  enemy: number;
}

export const MELEE_ATTACK_RANGE = 1;
export const MONK_VISION_RADIUS = 9;

export const UNIT_MAX_HP: Record<UnitType, number> = {
  villager: 25,
  scout: 45,
  militia: 40,
  spearman: 45,
  archer: 30,
  skirmisher: 30,
  'elite-skirmisher': 35,
  'eagle-warrior': 50, // units.csv
  'elite-eagle-warrior': 60, // units.csv
  'hand-cannoneer': 35, // units.csv
  knight: 100,
  crossbowman: 35,
  pikeman: 55,
  'light-cavalry': 60,
  camel: 100,
  'cavalry-archer': 50,
  mangonel: 50,
  scorpion: 40,
  'battering-ram': 175,
  monk: 30,
  longbowman: 35,
  arbalest: 40,
  halberdier: 60,
  hussar: 75,
  'heavy-cavalry-archer': 60,
  cavalier: 120,
  champion: 70,
  'elite-longbowman': 40,
  onager: 60,
  'siege-onager': 70,
  'heavy-scorpion': 50,
  'siege-ram': 270,
  'capped-ram': 200,
  'bombard-cannon': 80,
  trebuchet: 150,
  petard: 50, // units.csv hit_points.
  'trade-cart': 70, // units.csv hit_points.
  'man-at-arms': 50,
  'long-swordsman': 60,
  'two-handed-swordsman': 65,
  paladin: 160,
  'heavy-camel': 120,
  'fishing-ship': 60,
  'transport-ship': 100, // units.csv: 100 HP.
  'galley': 120,
  'war-galley': 135,
  'galleon': 165,
  'fire-ship': 100,
  'fast-fire-ship': 120,
  'demolition-ship': 50,
  'heavy-demolition-ship': 60,
  'cannon-galleon': 120,
  'elite-cannon-galleon': 150,
  'jaguar-warrior': 50,
  'cataphract': 110,
  'woad-raider': 65,
  'chu-ko-nu': 45,
  'throwing-axeman': 50,
  'huskarl': 60,
  'tarkan': 90,
  'samurai': 60,
  'war-wagon': 150,
  'plumed-archer': 50,
  'mangudai': 60,
  'war-elephant': 450,
  'mameluke': 65,
  'conquistador': 55,
  'teutonic-knight': 70,
  'janissary': 44,
  'berserk': 55,
  'turtle-ship': 200,
  'longboat': 130,
  'elite-jaguar-warrior': 75,
  'elite-cataphract': 150,
  'elite-woad-raider': 80,
  'elite-chu-ko-nu': 50,
  'elite-throwing-axeman': 60,
  'elite-huskarl': 70,
  'elite-tarkan': 150,
  'elite-samurai': 80,
  'elite-war-wagon': 200,
  'elite-plumed-archer': 65,
  'elite-mangudai': 60,
  'elite-war-elephant': 600,
  'elite-mameluke': 80,
  'elite-conquistador': 70,
  'elite-teutonic-knight': 100,
  'elite-janissary': 50,
  'elite-berserk': 72,
  'elite-turtle-ship': 300,
  'elite-longboat': 160,
};

export const UNIT_ATTACK_DAMAGE: Record<UnitType, number> = {
  villager: 3,
  scout: 3,
  militia: 4,
  spearman: 3,
  archer: 4,
  skirmisher: 2,
  'elite-skirmisher': 3,
  'eagle-warrior': 7, // units.csv (the Castle-Age row, the trainable one)
  'elite-eagle-warrior': 9, // units.csv
  'hand-cannoneer': 17, // units.csv — the hardest single hit any archer-role unit lands
  knight: 10,
  crossbowman: 5,
  pikeman: 4,
  'light-cavalry': 7,
  camel: 5,
  'cavalry-archer': 6,
  mangonel: 40,
  scorpion: 12,
  'battering-ram': 2,
  monk: 0,
  longbowman: 6,
  arbalest: 6,
  halberdier: 6,
  hussar: 7,
  'heavy-cavalry-archer': 7,
  cavalier: 12,
  champion: 13,
  'elite-longbowman': 7,
  onager: 50,
  'siege-onager': 75,
  'heavy-scorpion': 16,
  'siege-ram': 3,
  'capped-ram': 3,
  'bombard-cannon': 40,
  trebuchet: 200,
  petard: 25, // units.csv attack, before its enormous building bonus.
  'trade-cart': 0, // units.csv attack 0: it carries goods, not weapons.
  'man-at-arms': 6,
  'long-swordsman': 9,
  'two-handed-swordsman': 11,
  paladin: 14,
  'heavy-camel': 7,
  'fishing-ship': 0,
  'transport-ship': 0, // Carries units; it does not fight.
  'galley': 6,
  'war-galley': 7,
  'galleon': 8,
  'fire-ship': 2,
  'fast-fire-ship': 3,
  'demolition-ship': 110,
  'heavy-demolition-ship': 140,
  'cannon-galleon': 35,
  'elite-cannon-galleon': 45,
  'jaguar-warrior': 10,
  'cataphract': 9,
  'woad-raider': 8,
  'chu-ko-nu': 8,
  'throwing-axeman': 7,
  'huskarl': 10,
  'tarkan': 7,
  'samurai': 8,
  'war-wagon': 9,
  'plumed-archer': 5,
  'mangudai': 6,
  'war-elephant': 15,
  'mameluke': 7,
  'conquistador': 16,
  'teutonic-knight': 12,
  'janissary': 17,
  'berserk': 9,
  'turtle-ship': 50,
  'longboat': 7,
  'elite-jaguar-warrior': 12,
  'elite-cataphract': 12,
  'elite-woad-raider': 13,
  'elite-chu-ko-nu': 8,
  'elite-throwing-axeman': 8,
  'elite-huskarl': 12,
  'elite-tarkan': 11,
  'elite-samurai': 12,
  'elite-war-wagon': 9,
  'elite-plumed-archer': 5,
  'elite-mangudai': 8,
  'elite-war-elephant': 20,
  'elite-mameluke': 10,
  'elite-conquistador': 18,
  'elite-teutonic-knight': 17,
  'elite-janissary': 22,
  'elite-berserk': 14,
  'elite-turtle-ship': 50,
  'elite-longboat': 8,
};

// The armor tables live in ./unitArmorTables (extracted for the 500-LOC
// budget); re-exported so existing `from './statTables'` imports keep working.
export { UNIT_MELEE_ARMOR, UNIT_PIERCE_ARMOR } from './unitArmorTables';

export const UNIT_RELOAD_TICKS: Record<UnitType, number> = {
  villager: 12,
  scout: 12,
  militia: 10,
  spearman: 10,
  archer: 20,
  skirmisher: 20,
  'elite-skirmisher': 22,
  'eagle-warrior': 20, // units.csv 2.0 s
  'elite-eagle-warrior': 20, // units.csv 2.0 s
  'hand-cannoneer': 34, // units.csv 3.45 s — slow enough that the 17 damage is not oppressive
  knight: 18,
  crossbowman: 20,
  pikeman: 10,
  'light-cavalry': 12,
  camel: 20,
  'cavalry-archer': 20,
  mangonel: 60,
  scorpion: 35,
  'battering-ram': 50,
  monk: 10,
  longbowman: 20,
  arbalest: 20,
  halberdier: 30,
  hussar: 20,
  'heavy-cavalry-archer': 20,
  cavalier: 18,
  champion: 20,
  'elite-longbowman': 20,
  onager: 60,
  'siege-onager': 60,
  'heavy-scorpion': 35,
  'siege-ram': 50,
  'capped-ram': 50,
  'bombard-cannon': 70,
  trebuchet: 100,
  // Reload is irrelevant to a unit consumed by its first attack; this is the
  // value units.csv carries (0) raised to a legal cadence.
  petard: 20,
  'trade-cart': 20, // never fires (attack 0); the reload is inert.
  'man-at-arms': 20,
  'long-swordsman': 20,
  'two-handed-swordsman': 20,
  paladin: 18,
  'heavy-camel': 20,
  'fishing-ship': 20,
  'transport-ship': 20,
  'galley': 30,
  'war-galley': 30,
  'galleon': 30,
  'fire-ship': 3,
  'fast-fire-ship': 3,
  'demolition-ship': 10,
  'heavy-demolition-ship': 10,
  'cannon-galleon': 100,
  'elite-cannon-galleon': 100,
  'jaguar-warrior': 20,
  'cataphract': 18,
  'woad-raider': 20,
  'chu-ko-nu': 36,
  'throwing-axeman': 20,
  'huskarl': 20,
  'tarkan': 21,
  'samurai': 14,
  'war-wagon': 25,
  'plumed-archer': 19,
  'mangudai': 17,
  'war-elephant': 20,
  'mameluke': 20,
  'conquistador': 29,
  'teutonic-knight': 20,
  'janissary': 35,
  'berserk': 20,
  'turtle-ship': 60,
  'longboat': 30,
  'elite-jaguar-warrior': 20,
  'elite-cataphract': 17,
  'elite-woad-raider': 20,
  'elite-chu-ko-nu': 38,
  'elite-throwing-axeman': 20,
  'elite-huskarl': 20,
  'elite-tarkan': 21,
  'elite-samurai': 14,
  'elite-war-wagon': 25,
  'elite-plumed-archer': 19,
  'elite-mangudai': 17,
  'elite-war-elephant': 20,
  'elite-mameluke': 20,
  'elite-conquistador': 29,
  'elite-teutonic-knight': 20,
  'elite-janissary': 34,
  'elite-berserk': 20,
  'elite-turtle-ship': 60,
  'elite-longboat': 30,
};

export const UNIT_ATTACK_RANGE: Record<UnitType, number> = {
  villager: MELEE_ATTACK_RANGE,
  scout: MELEE_ATTACK_RANGE,
  militia: MELEE_ATTACK_RANGE,
  spearman: MELEE_ATTACK_RANGE,
  archer: 4,
  skirmisher: 4,
  'elite-skirmisher': 5,
  'eagle-warrior': MELEE_ATTACK_RANGE,
  'elite-eagle-warrior': MELEE_ATTACK_RANGE,
  'hand-cannoneer': 7, // units.csv
  knight: MELEE_ATTACK_RANGE,
  crossbowman: 5,
  pikeman: MELEE_ATTACK_RANGE,
  'light-cavalry': MELEE_ATTACK_RANGE,
  camel: MELEE_ATTACK_RANGE,
  'cavalry-archer': 4,
  mangonel: 7,
  scorpion: 7,
  'battering-ram': MELEE_ATTACK_RANGE,
  monk: 0,
  longbowman: 6,
  arbalest: 5,
  halberdier: MELEE_ATTACK_RANGE,
  hussar: MELEE_ATTACK_RANGE,
  'heavy-cavalry-archer': 4,
  cavalier: MELEE_ATTACK_RANGE,
  champion: MELEE_ATTACK_RANGE,
  'elite-longbowman': 6,
  onager: 8,
  'siege-onager': 8,
  'heavy-scorpion': 7,
  'siege-ram': MELEE_ATTACK_RANGE,
  'capped-ram': MELEE_ATTACK_RANGE,
  'bombard-cannon': 12,
  trebuchet: 16,
  petard: MELEE_ATTACK_RANGE, // units.csv range 0: it walks up to the wall.
  'trade-cart': MELEE_ATTACK_RANGE, // attack 0 — the range is never used.
  'man-at-arms': MELEE_ATTACK_RANGE,
  'long-swordsman': MELEE_ATTACK_RANGE,
  'two-handed-swordsman': MELEE_ATTACK_RANGE,
  paladin: MELEE_ATTACK_RANGE,
  'heavy-camel': MELEE_ATTACK_RANGE,
  'fishing-ship': MELEE_ATTACK_RANGE,
  'transport-ship': MELEE_ATTACK_RANGE,
  'galley': 5,
  'war-galley': 6,
  'galleon': 7,
  'fire-ship': 2,
  'fast-fire-ship': 2,
  'demolition-ship': 1,
  'heavy-demolition-ship': 1,
  'cannon-galleon': 13,
  'elite-cannon-galleon': 15,
  'jaguar-warrior': MELEE_ATTACK_RANGE,
  'cataphract': MELEE_ATTACK_RANGE,
  'woad-raider': MELEE_ATTACK_RANGE,
  'chu-ko-nu': 4,
  'throwing-axeman': 3,
  'huskarl': MELEE_ATTACK_RANGE,
  'tarkan': MELEE_ATTACK_RANGE,
  'samurai': MELEE_ATTACK_RANGE,
  'war-wagon': 4,
  'plumed-archer': 4,
  'mangudai': 4,
  'war-elephant': MELEE_ATTACK_RANGE,
  'mameluke': 3,
  'conquistador': 6,
  'teutonic-knight': MELEE_ATTACK_RANGE,
  'janissary': 8,
  'berserk': MELEE_ATTACK_RANGE,
  'turtle-ship': 6,
  'longboat': 6,
  'elite-jaguar-warrior': MELEE_ATTACK_RANGE,
  'elite-cataphract': MELEE_ATTACK_RANGE,
  'elite-woad-raider': MELEE_ATTACK_RANGE,
  'elite-chu-ko-nu': 6,
  'elite-throwing-axeman': 4,
  'elite-huskarl': MELEE_ATTACK_RANGE,
  'elite-tarkan': MELEE_ATTACK_RANGE,
  'elite-samurai': MELEE_ATTACK_RANGE,
  'elite-war-wagon': 5,
  'elite-plumed-archer': 5,
  'elite-mangudai': 4,
  'elite-war-elephant': MELEE_ATTACK_RANGE,
  'elite-mameluke': 3,
  'elite-conquistador': 6,
  'elite-teutonic-knight': MELEE_ATTACK_RANGE,
  'elite-janissary': 8,
  'elite-berserk': MELEE_ATTACK_RANGE,
  'elite-turtle-ship': 6,
  'elite-longboat': 7,
};

// Classification sets + wildlife profiles live in ./unitClassSets (extracted to
// keep this file under the 500-LOC budget); re-exported so existing imports of
// `from './statTables'` keep working.
export {
  ARCHER_LINE_UNITS,
  CAVALRY_ARCHER_UNITS,
  CAVALRY_UNITS,
  INFANTRY_UNITS,
  MELEE_UNITS,
  MOUNTED_UNITS,
  STATIC_MEMORABLE_RESOURCE_TYPES,
  UNIT_MIN_ATTACK_RANGE,
  WILDLIFE_PROFILES,
} from './unitClassSets';
