// The two per-unit ARMOR tables, split out of ./statTables.ts when the roster's
// elite tier pushed that file past the 500-LOC budget. Same shape, same source
// (design/stats/units.csv `armor`, "melee/pierce"); statTables re-exports both
// names so existing imports keep working.

import type { UnitType } from '../unitTypes';

// Base PIERCE armor per unit, from design/stats/units.csv (the `melee/pierce`
// armor column, second value). Data-driven combat Slice 1: pierce attacks
// (archers/skirmishers/siege/towers) are reduced by this instead of the single
// melee `armor`. The standouts drive AoE2 counter-play: skirmishers (3) shrug
// off archer fire, rams (180+) are near-immune to arrows, cavalry/scout line
// carry 2. Melee base armor stays 0 here (unchanged prototype behaviour); the
// CSV's melee column + armor classes are Slice 2.
export const UNIT_PIERCE_ARMOR: Record<UnitType, number> = {
  villager: 0,
  scout: 2,
  militia: 1,
  spearman: 0,
  archer: 0,
  skirmisher: 3,
  'elite-skirmisher': 4,
  'eagle-warrior': 2, // units.csv 0/2
  'elite-eagle-warrior': 4, // units.csv 0/4
  'hand-cannoneer': 0, // units.csv 1/0
  knight: 2,
  crossbowman: 0,
  pikeman: 0,
  'light-cavalry': 2,
  camel: 0,
  'cavalry-archer': 0,
  mangonel: 6,
  scorpion: 6,
  'battering-ram': 180,
  monk: 0,
  longbowman: 0,
  arbalest: 0,
  halberdier: 0,
  hussar: 2,
  'heavy-cavalry-archer': 0,
  cavalier: 2,
  champion: 1,
  'elite-longbowman': 1,
  onager: 7,
  'siege-onager': 8,
  'heavy-scorpion': 7,
  'siege-ram': 195,
  'capped-ram': 190,
  'bombard-cannon': 5,
  trebuchet: 150,
  petard: 0, // units.csv armour 0/2: no melee armour.
  'trade-cart': 0, // units.csv armour 0/0.
  'trade-cog': 0, // units.csv armour 0/6: no melee armour.
  missionary: 0, // units.csv armour 0/0.
  'man-at-arms': 1,
  'long-swordsman': 1,
  'two-handed-swordsman': 1,
  paladin: 3,
  'heavy-camel': 0,
  'fishing-ship': 6,
  'transport-ship': 8, // units.csv armor 4/8: pierce.
  'galley': 6,
  'war-galley': 6,
  'galleon': 8,
  'fire-ship': 6,
  'fast-fire-ship': 8,
  'demolition-ship': 3,
  'heavy-demolition-ship': 3,
  'cannon-galleon': 6,
  'elite-cannon-galleon': 8,
  'jaguar-warrior': 0,
  'cataphract': 1,
  'woad-raider': 1,
  'chu-ko-nu': 0,
  'throwing-axeman': 0,
  'huskarl': 6,
  'tarkan': 2,
  'samurai': 1,
  'war-wagon': 3,
  'plumed-archer': 1,
  'mangudai': 0,
  'war-elephant': 2,
  'mameluke': 0,
  'conquistador': 2,
  'teutonic-knight': 2,
  'janissary': 0,
  'berserk': 1,
  'turtle-ship': 5,
  'longboat': 6,
  'elite-jaguar-warrior': 0,
  'elite-cataphract': 1,
  'elite-woad-raider': 1,
  'elite-chu-ko-nu': 0,
  'elite-throwing-axeman': 0,
  'elite-huskarl': 8,
  'elite-tarkan': 3,
  'elite-samurai': 1,
  'elite-war-wagon': 4,
  'elite-plumed-archer': 2,
  'elite-mangudai': 1,
  'elite-war-elephant': 3,
  'elite-mameluke': 0,
  'elite-conquistador': 2,
  'elite-teutonic-knight': 2,
  'elite-janissary': 0,
  'elite-berserk': 1,
  'elite-turtle-ship': 6,
  'elite-longboat': 8,
};

// Base MELEE armor per unit, from design/stats/units.csv (the `melee/pierce`
// armor column, FIRST value). Data-driven combat Slice 2a: melee attacks are
// reduced by this base value plus the unit's armor-tech bonus. Mostly 0; the
// standouts are the cavalry line (knight/cavalier/paladin 2 — meaty vs melee)
// plus champion / trebuchet / heavy-cavalry-archer 1 and bombard cannon 2.
export const UNIT_MELEE_ARMOR: Record<UnitType, number> = {
  villager: 0,
  scout: 0,
  militia: 0,
  spearman: 0,
  archer: 0,
  skirmisher: 0,
  'elite-skirmisher': 0,
  'eagle-warrior': 0, // units.csv 0/2
  'elite-eagle-warrior': 0, // units.csv 0/4
  'hand-cannoneer': 1, // units.csv 1/0
  knight: 2,
  crossbowman: 0,
  pikeman: 0,
  'light-cavalry': 0,
  camel: 0,
  'cavalry-archer': 0,
  mangonel: 0,
  scorpion: 0,
  'battering-ram': 0,
  monk: 0,
  longbowman: 0,
  arbalest: 0,
  halberdier: 0,
  hussar: 0,
  'heavy-cavalry-archer': 1,
  cavalier: 2,
  champion: 1,
  'elite-longbowman': 0,
  onager: 0,
  'siege-onager': 0,
  'heavy-scorpion': 0,
  'siege-ram': 0,
  'capped-ram': 0,
  'bombard-cannon': 2,
  trebuchet: 1,
  petard: 2, // units.csv armour 0/2: two pierce.
  'trade-cart': 0, // units.csv armour 0/0.
  'trade-cog': 6, // units.csv armour 0/6: six pierce, a tough hull.
  missionary: 0, // units.csv armour 0/0.
  'man-at-arms': 0,
  'long-swordsman': 0,
  'two-handed-swordsman': 0,
  paladin: 2,
  'heavy-camel': 0,
  'fishing-ship': 0,
  'transport-ship': 4, // units.csv armor 4/8: melee.
  'galley': 0,
  'war-galley': 0,
  'galleon': 0,
  'fire-ship': 0,
  'fast-fire-ship': 0,
  'demolition-ship': 0,
  'heavy-demolition-ship': 0,
  'cannon-galleon': 0,
  'elite-cannon-galleon': 0,
  'jaguar-warrior': 1,
  'cataphract': 2,
  'woad-raider': 0,
  'chu-ko-nu': 0,
  'throwing-axeman': 0,
  'huskarl': 0,
  'tarkan': 1,
  'samurai': 1,
  'war-wagon': 0,
  'plumed-archer': 0,
  'mangudai': 0,
  'war-elephant': 1,
  'mameluke': 0,
  'conquistador': 2,
  'teutonic-knight': 5,
  'janissary': 1,
  'berserk': 0,
  'turtle-ship': 6,
  'longboat': 0,
  'elite-jaguar-warrior': 2,
  'elite-cataphract': 2,
  'elite-woad-raider': 0,
  'elite-chu-ko-nu': 0,
  'elite-throwing-axeman': 1,
  'elite-huskarl': 0,
  'elite-tarkan': 1,
  'elite-samurai': 1,
  'elite-war-wagon': 0,
  'elite-plumed-archer': 0,
  'elite-mangudai': 0,
  'elite-war-elephant': 1,
  'elite-mameluke': 1,
  'elite-conquistador': 2,
  'elite-teutonic-knight': 10,
  'elite-janissary': 2,
  'elite-berserk': 2,
  'elite-turtle-ship': 8,
  'elite-longboat': 0,
};
