import type { UnitType } from '../../game/simulation/types';

export type UnitRole =
  | 'villager'
  | 'infantry'
  | 'archer'
  | 'cavalry'
  | 'cavalry-archer'
  | 'siege'
  | 'monk'
  | 'ship'; // M5 naval: hull + mast, sharing nothing with a land silhouette.

// Render-owned, exhaustive visual grouping used by voxel recipes and DOM
// glyphs. It deliberately stays independent from combat classifications.
const UNIT_ROLES = {
  villager: 'villager',
  militia: 'infantry',
  'man-at-arms': 'infantry',
  'long-swordsman': 'infantry',
  'two-handed-swordsman': 'infantry',
  champion: 'infantry',
  spearman: 'infantry',
  pikeman: 'infantry',
  halberdier: 'infantry',
  archer: 'archer',
  crossbowman: 'archer',
  arbalest: 'archer',
  skirmisher: 'archer',
  'elite-skirmisher': 'archer',
  longbowman: 'archer',
  'elite-longbowman': 'archer',
  scout: 'cavalry',
  'light-cavalry': 'cavalry',
  hussar: 'cavalry',
  camel: 'cavalry',
  'heavy-camel': 'cavalry',
  knight: 'cavalry',
  cavalier: 'cavalry',
  paladin: 'cavalry',
  'cavalry-archer': 'cavalry-archer',
  'heavy-cavalry-archer': 'cavalry-archer',
  mangonel: 'siege',
  onager: 'siege',
  scorpion: 'siege',
  'heavy-scorpion': 'siege',
  'battering-ram': 'siege',
  'siege-ram': 'siege',
  'capped-ram': 'siege',
  'siege-onager': 'siege',
  'bombard-cannon': 'siege',
  trebuchet: 'siege',
  'fishing-ship': 'ship',
  'transport-ship': 'ship',
  'galley': 'ship',
  'war-galley': 'ship',
  'galleon': 'ship',
  'fire-ship': 'ship',
  'fast-fire-ship': 'ship',
  'demolition-ship': 'ship',
  'heavy-demolition-ship': 'ship',
  'cannon-galleon': 'ship',
  'elite-cannon-galleon': 'ship',
  'jaguar-warrior': 'infantry',
  'cataphract': 'cavalry',
  'woad-raider': 'infantry',
  'chu-ko-nu': 'archer',
  'throwing-axeman': 'archer',
  'huskarl': 'infantry',
  'tarkan': 'cavalry',
  'samurai': 'infantry',
  'war-wagon': 'cavalry-archer',
  'plumed-archer': 'archer',
  'mangudai': 'cavalry-archer',
  'war-elephant': 'cavalry',
  'mameluke': 'cavalry',
  'conquistador': 'cavalry-archer',
  'teutonic-knight': 'infantry',
  'janissary': 'archer',
  'berserk': 'infantry',
  'turtle-ship': 'ship',
  'longboat': 'ship',
  'elite-jaguar-warrior': 'infantry',
  'elite-cataphract': 'cavalry',
  'elite-woad-raider': 'infantry',
  'elite-chu-ko-nu': 'archer',
  'elite-throwing-axeman': 'archer',
  'elite-huskarl': 'infantry',
  'elite-tarkan': 'cavalry',
  'elite-samurai': 'infantry',
  'elite-war-wagon': 'cavalry-archer',
  'elite-plumed-archer': 'archer',
  'elite-mangudai': 'cavalry-archer',
  'elite-war-elephant': 'cavalry',
  'elite-mameluke': 'cavalry',
  'elite-conquistador': 'cavalry-archer',
  'elite-teutonic-knight': 'infantry',
  'elite-janissary': 'archer',
  'elite-berserk': 'infantry',
  'elite-turtle-ship': 'ship',
  'elite-longboat': 'ship',
  monk: 'monk',
} as const satisfies Record<UnitType, UnitRole>;

export function unitRole(unitType: UnitType): UnitRole {
  return UNIT_ROLES[unitType];
}
