// Exhaustive UnitType lookup shared by renderer-neutral selection input. The
// `satisfies Record<UnitType, true>` clause on `ALL_UNIT_TYPES` is the
// load-bearing piece — adding a new unit to `UnitType` in
// `src/game/simulation/types.ts` forces a TypeScript error here if the
// lookup isn't updated. Iter-3 V3-3 introduced this guard after the
// FU2-era unit-type drift.

import type { SelectionState, UnitType } from '../game/simulation/types';

export const ALL_UNIT_TYPES = {
  villager: true,
  scout: true,
  militia: true,
  spearman: true,
  archer: true,
  skirmisher: true,
  knight: true,
  crossbowman: true,
  pikeman: true,
  'light-cavalry': true,
  camel: true,
  'cavalry-archer': true,
  monk: true,
  mangonel: true,
  scorpion: true,
  'battering-ram': true,
  longbowman: true,
  arbalest: true,
  halberdier: true,
  hussar: true,
  'heavy-cavalry-archer': true,
  cavalier: true,
  champion: true,
  'elite-longbowman': true,
  onager: true,
  'heavy-scorpion': true,
  'siege-ram': true,
  'capped-ram': true,
  'siege-onager': true,
  'elite-skirmisher': true,
  'bombard-cannon': true,
  trebuchet: true,
  'fishing-ship': true,
  'transport-ship': true,
  'galley': true,
  'war-galley': true,
  'galleon': true,
  'fire-ship': true,
  'fast-fire-ship': true,
  'demolition-ship': true,
  'heavy-demolition-ship': true,
  'cannon-galleon': true,
  'elite-cannon-galleon': true,
  'jaguar-warrior': true,
  'cataphract': true,
  'woad-raider': true,
  'chu-ko-nu': true,
  'throwing-axeman': true,
  'huskarl': true,
  'tarkan': true,
  'samurai': true,
  'war-wagon': true,
  'plumed-archer': true,
  'mangudai': true,
  'war-elephant': true,
  'mameluke': true,
  'conquistador': true,
  'teutonic-knight': true,
  'janissary': true,
  'berserk': true,
  'turtle-ship': true,
  'longboat': true,
  'elite-jaguar-warrior': true,
  'elite-cataphract': true,
  'elite-woad-raider': true,
  'elite-chu-ko-nu': true,
  'elite-throwing-axeman': true,
  'elite-huskarl': true,
  'elite-tarkan': true,
  'elite-samurai': true,
  'elite-war-wagon': true,
  'elite-plumed-archer': true,
  'elite-mangudai': true,
  'elite-war-elephant': true,
  'elite-mameluke': true,
  'elite-conquistador': true,
  'elite-teutonic-knight': true,
  'elite-janissary': true,
  'elite-berserk': true,
  'elite-turtle-ship': true,
  'elite-longboat': true,
  'man-at-arms': true,
  'long-swordsman': true,
  'two-handed-swordsman': true,
  paladin: true,
  'heavy-camel': true,
} as const satisfies Record<UnitType, true>;

export function isUnitType(
  entityType: SelectionState['selectedEntityType'],
): entityType is UnitType {
  // `hasOwn`, not `in`: the latter walks the prototype chain, so an object
  // literal answers true for 'toString', 'constructor', and every other
  // Object.prototype member.
  return entityType !== null && Object.hasOwn(ALL_UNIT_TYPES, entityType);
}
